"""
Common pediatric drugs for Smart-Elixir safety checks.
Dosing ranges are Harriet Lane–aligned typical pediatric values for decision support.
Always confirm with current local protocol / full monograph before prescribing.
"""

def _d(
    min_mg_kg,
    max_mg_kg,
    abs_single,
    max_daily_mg_kg,
    abs_daily,
    freq,
    routes,
    how,
    notes,
    category="General",
    contraindications="",
    indications="",
):
    return {
        "min_mg_kg": float(min_mg_kg),
        "max_mg_kg": float(max_mg_kg),
        "absolute_max_single_mg": float(abs_single),
        "max_daily_mg_kg": float(max_daily_mg_kg),
        "absolute_max_daily_mg": float(abs_daily),
        "default_doses_per_day": int(freq),
        "routes": list(routes),
        "how_to_take": how,
        "notes": notes,
        "category": category,
        "contraindications": contraindications,
        "indications": indications,
        "source": "Harriet Lane / Nelson–aligned pediatric formulary (verify locally)",
    }

PEDIATRIC_DRUG_DB = {
    # --- Analgesic / Antipyretic ---
    "PARACETAMOL": _d(10, 15, 1000, 90, 4000, 4, ["PO", "PR", "IV"],
        "Give by mouth (syrup/tablet) or rectum as advised. Space doses 4–6 hours apart. Do not exceed 5 doses in 24 hours.",
        "PO/PR 10–15 mg/kg/dose Q4–6 hr; max ~90 mg/kg/day or 4 g/day.", "Analgesic"),
    "IBUPROFEN": _d(5, 10, 800, 40, 2400, 4, ["PO", "IV"],
        "Give by mouth after food if possible. Space 6–8 hours. Avoid if dehydrated or kidney problem.",
        "5–10 mg/kg/dose PO Q6–8 hr; max ~40 mg/kg/day.", "Analgesic"),
    "ASPIRIN": _d(10, 15, 650, 60, 4000, 4, ["PO"],
        "Give by mouth with food. Not for viral illness in children (Reye risk) unless doctor advises.",
        "Use only if specifically indicated; verify indication carefully.", "Analgesic"),
    "NAPROXEN": _d(5, 7, 500, 20, 1000, 2, ["PO"],
        "Give by mouth with food twice daily as advised.",
        "Typically ~5–7 mg/kg/dose PO Q12 hr.", "Analgesic"),
    "DICLOFENAC": _d(0.5, 1, 50, 3, 150, 3, ["PO", "PR"],
        "Give by mouth or rectum with food as advised.",
        "About 0.5–1 mg/kg/dose; max limited in children.", "Analgesic"),
    "KETOROLAC": _d(0.5, 0.5, 30, 2, 120, 4, ["IV", "IM", "PO"],
        "Injection or oral short course only as prescribed. Not for long use.",
        "0.5 mg/kg/dose Q6 hr; max 30 mg/dose; short duration.", "Analgesic"),
    "TRAMADOL": _d(1, 2, 100, 8, 400, 4, ["PO", "IV"],
        "Give exactly as prescribed. May cause sleepiness/nausea.",
        "Caution in young children; confirm age restrictions.", "Analgesic"),
    "MORPHINE": _d(0.05, 0.1, 10, 0.4, 40, 4, ["IV", "PO", "IM", "SC"],
        "Hospital-supervised opioid. Monitor breathing.",
        "IV 0.05–0.1 mg/kg/dose; titrate carefully.", "Analgesic"),

    # --- Antibiotics ---
    "AMOXICILLIN": _d(8, 17, 1000, 50, 3000, 3, ["PO"],
        "Give by mouth every 8 hours (or as written). Complete full course even if child feels better.",
        "Standard 25–50 mg/kg/day ÷ Q8–12 hr; high-dose 80–90 mg/kg/day for AOM/CAP.", "Antibiotic"),
    "AMOXICILLIN-CLAVULANATE": _d(7, 15, 875, 45, 2000, 2, ["PO"],
        "Give by mouth with food to reduce stomach upset. Finish full course.",
        "Based on amoxicillin component; ES high-dose regimens exist.", "Antibiotic"),
    "AMPICILLIN": _d(25, 50, 2000, 200, 8000, 4, ["IV", "IM", "PO"],
        "Usually IV/IM in hospital. Oral only if prescribed.",
        "Common IV 100–200 mg/kg/day ÷ Q6 hr depending on indication.", "Antibiotic"),
    "AZITHROMYCIN": _d(5, 10, 500, 10, 500, 1, ["PO", "IV"],
        "Give by mouth once daily. Can take with or without food (suspension: follow label).",
        "Often 10 mg/kg day 1 then 5 mg/kg days 2–5, or 10 mg/kg daily x 3 days.", "Antibiotic"),
    "CLARITHROMYCIN": _d(7.5, 7.5, 500, 15, 1000, 2, ["PO"],
        "Give by mouth twice daily. Finish course.",
        "15 mg/kg/day ÷ BID.", "Antibiotic"),
    "ERYTHROMYCIN": _d(10, 15, 500, 50, 2000, 4, ["PO", "IV"],
        "Give by mouth as scheduled. May upset stomach.",
        "30–50 mg/kg/day ÷ Q6–8 hr.", "Antibiotic"),
    "CEPHALEXIN": _d(6, 12, 500, 50, 2000, 4, ["PO"],
        "Give by mouth 3–4 times daily. Finish course.",
        "25–50 mg/kg/day ÷ Q6–8 hr; higher for some infections.", "Antibiotic"),
    "CEFADROXIL": _d(15, 15, 1000, 30, 2000, 2, ["PO"],
        "Give by mouth once or twice daily.",
        "About 30 mg/kg/day ÷ Q12–24 hr.", "Antibiotic"),
    "CEFIXIME": _d(4, 8, 400, 8, 400, 1, ["PO"],
        "Give by mouth once or twice daily as prescribed.",
        "8 mg/kg/day PO ÷ Q12–24 hr.", "Antibiotic"),
    "CEFPODOXIME": _d(5, 5, 200, 10, 400, 2, ["PO"],
        "Give by mouth twice daily with food.",
        "10 mg/kg/day ÷ BID.", "Antibiotic"),
    "CEFDINIR": _d(7, 7, 300, 14, 600, 1, ["PO"],
        "Give by mouth once or twice daily. Avoid iron at same time if possible.",
        "14 mg/kg/day ÷ Q12–24 hr.", "Antibiotic"),
    "CEFUROXIME": _d(10, 15, 500, 30, 1000, 2, ["PO", "IV"],
        "Oral tablets/suspension or IV as prescribed. Oral: with food.",
        "PO ~20–30 mg/kg/day ÷ BID; IV dosing differs.", "Antibiotic"),
    "CEFTRIAXONE": _d(50, 75, 2000, 100, 4000, 1, ["IV", "IM"],
        "Injection only (hospital/clinic). Do not give at home unless trained.",
        "50–100 mg/kg/day IV/IM (meningitis higher; max limits apply).", "Antibiotic"),
    "CEFOTAXIME": _d(50, 50, 2000, 200, 8000, 3, ["IV", "IM"],
        "Hospital injection. Given several times daily.",
        "100–200 mg/kg/day ÷ Q6–8 hr.", "Antibiotic"),
    "CEFTAZIDIME": _d(30, 50, 2000, 150, 6000, 3, ["IV", "IM"],
        "Hospital injection.",
        "90–150 mg/kg/day ÷ Q8 hr.", "Antibiotic"),
    "CEFEPIME": _d(50, 50, 2000, 150, 4000, 2, ["IV"],
        "Hospital IV only.",
        "100–150 mg/kg/day ÷ Q8–12 hr.", "Antibiotic"),
    "CEFAZOLIN": _d(25, 25, 2000, 100, 6000, 3, ["IV", "IM"],
        "Hospital injection.",
        "50–100 mg/kg/day ÷ Q8 hr.", "Antibiotic"),
    "CIPROFLOXACIN": _d(10, 15, 750, 30, 1500, 2, ["PO", "IV"],
        "Give by mouth twice daily with water. Avoid dairy/antacids near dose if advised.",
        "20–30 mg/kg/day ÷ BID; use when benefits outweigh risks.", "Antibiotic"),
    "LEVOFLOXACIN": _d(8, 10, 750, 20, 750, 1, ["PO", "IV"],
        "Once daily by mouth or IV as prescribed.",
        "Age/indication restricted; confirm carefully.", "Antibiotic"),
    "METRONIDAZOLE": _d(7.5, 10, 500, 30, 2000, 3, ["PO", "IV"],
        "Give by mouth with food if stomach upset. Avoid alcohol in older teens.",
        "30 mg/kg/day ÷ Q6–8 hr common for many indications.", "Antibiotic"),
    "CLINDAMYCIN": _d(5, 10, 600, 40, 1800, 3, ["PO", "IV"],
        "Give by mouth with full glass of water. Report severe diarrhea.",
        "20–40 mg/kg/day ÷ Q6–8 hr.", "Antibiotic"),
    "COTRIMOXAZOLE": _d(3, 5, 160, 10, 320, 2, ["PO", "IV"],
        "Give by mouth twice daily (dose as trimethoprim component). Keep hydrated.",
        "TMP 6–10 mg/kg/day ÷ BID (treatment).", "Antibiotic"),
    "TRIMETHOPRIM": _d(2, 3, 160, 6, 320, 2, ["PO"],
        "Give by mouth as prescribed.",
        "Often 2–3 mg/kg/dose BID depending on indication.", "Antibiotic"),
    "NITROFURANTOIN": _d(1.25, 1.75, 100, 7, 400, 4, ["PO"],
        "Give by mouth with food. Not for young infants unless specialist advises.",
        "5–7 mg/kg/day ÷ Q6 hr for treatment.", "Antibiotic"),
    "DOXYCYCLINE": _d(1, 2, 100, 4, 200, 2, ["PO", "IV"],
        "Give by mouth with water; sit upright. Avoid in <8 yr unless necessary.",
        "2–4 mg/kg/day ÷ Q12–24 hr.", "Antibiotic"),
    "LINEZOLID": _d(10, 10, 600, 30, 1200, 2, ["PO", "IV"],
        "Give exactly as prescribed (PO or IV).",
        "30 mg/kg/day ÷ BID (age-based variations).", "Antibiotic"),
    "VANCOMYCIN": _d(10, 15, 1000, 60, 4000, 4, ["IV"],
        "Hospital IV only. Levels often monitored.",
        "40–60 mg/kg/day ÷ Q6–8 hr (indication-dependent).", "Antibiotic"),
    "GENTAMICIN": _d(2, 2.5, 120, 7.5, 300, 3, ["IV", "IM"],
        "Hospital injection. Kidney/hearing monitoring may be needed.",
        "Traditional or extended-interval regimens; confirm protocol.", "Antibiotic"),
    "AMIKACIN": _d(5, 7.5, 500, 22.5, 1500, 3, ["IV", "IM"],
        "Hospital injection.",
        "15–22.5 mg/kg/day traditional ÷ Q8 hr or once-daily protocols.", "Antibiotic"),
    "MEROPENEM": _d(20, 40, 2000, 120, 6000, 3, ["IV"],
        "Hospital IV only.",
        "60–120 mg/kg/day ÷ Q8 hr.", "Antibiotic"),
    "PIPERACILLIN-TAZOBACTAM": _d(75, 100, 4000, 400, 16000, 4, ["IV"],
        "Hospital IV only (piperacillin component).",
        "240–400 mg/kg/day piperacillin ÷ Q6–8 hr.", "Antibiotic"),
    "PENICILLIN-V": _d(6, 12, 500, 50, 2000, 3, ["PO"],
        "Give by mouth on empty stomach if tolerated, or as advised.",
        "25–50 mg/kg/day ÷ Q6–8 hr.", "Antibiotic"),
    "FLUCLAXACILLIN": _d(12.5, 25, 500, 100, 2000, 4, ["PO", "IV"],
        "Give by mouth on empty stomach if possible.",
        "50–100 mg/kg/day ÷ Q6 hr.", "Antibiotic"),
    "CLOXACILLIN": _d(12.5, 25, 500, 100, 2000, 4, ["PO", "IV"],
        "Give by mouth before food if advised.",
        "50–100 mg/kg/day ÷ Q6 hr.", "Antibiotic"),

    # --- Antihistamine / Allergy ---
    "CETIRIZINE": _d(0.25, 0.25, 10, 0.25, 10, 1, ["PO"],
        "Give by mouth once daily, with or without food. May cause mild sleepiness.",
        "Age-based often used: 2.5–5 mg (2–5 yr), 5–10 mg (≥6 yr); ~0.25 mg/kg.", "Antihistamine"),
    "LEVOCETIRIZINE": _d(0.125, 0.125, 5, 0.125, 5, 1, ["PO"],
        "Give by mouth once daily in evening if sleepiness occurs.",
        "Age-banded dosing common; verify by age.", "Antihistamine"),
    "LORATADINE": _d(0.2, 0.2, 10, 0.2, 10, 1, ["PO"],
        "Give by mouth once daily.",
        "Age-banded; often 5–10 mg once daily.", "Antihistamine"),
    "DESLORATADINE": _d(0.1, 0.1, 5, 0.1, 5, 1, ["PO"],
        "Give by mouth once daily.",
        "Age-banded syrup/tablet dosing.", "Antihistamine"),
    "FEXOFENADINE": _d(1, 2, 180, 4, 180, 2, ["PO"],
        "Give by mouth with water. Avoid fruit juices if labeled.",
        "Age-banded (30–60 mg BID etc.).", "Antihistamine"),
    "DIPHENHYDRAMINE": _d(1, 1.25, 50, 5, 300, 4, ["PO", "IV", "IM"],
        "Give by mouth; causes sleepiness. Do not use to make infant sleep.",
        "5 mg/kg/day ÷ Q6 hr; max 50 mg/dose.", "Antihistamine"),
    "HYDROXYZINE": _d(0.5, 1, 50, 2, 100, 3, ["PO", "IM"],
        "Give by mouth as prescribed. Sedating.",
        "2 mg/kg/day ÷ Q6–8 hr common.", "Antihistamine"),
    "CHLORPHENIRAMINE": _d(0.1, 0.2, 4, 0.35, 24, 3, ["PO"],
        "Give by mouth. May cause sleepiness.",
        "Age-banded classic dosing.", "Antihistamine"),
    "PROMETHAZINE": _d(0.25, 0.5, 25, 1, 50, 3, ["PO", "IM", "PR"],
        "Give only if prescribed. Avoid in young children for cough/cold.",
        "Caution <2 years; confirm indication.", "Antihistamine"),

    # --- Antiemetic / GI ---
    "ONDANSETRON": _d(0.1, 0.15, 8, 0.45, 24, 3, ["PO", "IV", "IM"],
        "Give by mouth or injection for vomiting as prescribed. Oral dissolve tablet: let melt on tongue.",
        "0.1–0.15 mg/kg/dose; max often 8 mg/dose.", "Antiemetic"),
    "DOMPERIDONE": _d(0.25, 0.5, 10, 1.2, 30, 3, ["PO"],
        "Give by mouth before meals. Short courses preferred.",
        "Typically 0.25–0.5 mg/kg/dose TID; cardiac caution.", "Antiemetic"),
    "METOCLOPRAMIDE": _d(0.1, 0.15, 10, 0.5, 30, 4, ["PO", "IV", "IM"],
        "Give as prescribed. Watch for unusual movements (EPS).",
        "0.1–0.15 mg/kg/dose; max 10 mg/dose.", "Antiemetic"),
    "OMEPRRAZOLE": _d(0.7, 1, 40, 2, 40, 1, ["PO", "IV"],
        "Give by mouth before breakfast. Capsules: do not crush delayed-release unless told.",
        "0.7–1.4 mg/kg/day (often once daily).", "GI"),
    "OMEPRAZOLE": _d(0.7, 1.4, 40, 2.8, 40, 1, ["PO", "IV"],
        "Give by mouth 30 minutes before food once daily (or as written).",
        "Usually 0.7–1.4 mg/kg/day PO.", "GI"),
    "PANTOPRAZOLE": _d(0.5, 1, 40, 2, 40, 1, ["PO", "IV"],
        "Give by mouth before food.",
        "About 1 mg/kg/day (max 40 mg).", "GI"),
    "RANITIDINE": _d(2, 4, 150, 8, 300, 2, ["PO", "IV"],
        "Availability limited in many regions; use only if prescribed.",
        "Historical dosing ~4–8 mg/kg/day ÷ BID.", "GI"),
    "FAMOTIDINE": _d(0.5, 1, 40, 2, 80, 2, ["PO", "IV"],
        "Give by mouth once or twice daily.",
        "1–2 mg/kg/day ÷ Q12–24 hr.", "GI"),
    "SUCRALFATE": _d(20, 20, 1000, 80, 4000, 4, ["PO"],
        "Give by mouth on empty stomach. Separate from other medicines if advised.",
        "40–80 mg/kg/day ÷ Q6 hr.", "GI"),
    "LACTULOSE": _d(0.5, 1, 30, 3, 90, 2, ["PO", "PR"],
        "Give by mouth; adjust to soft stools. Mix with water/juice if needed. (Dose in ml often used.)",
        "Often 1–2 ml/kg/day (product-specific); confirm syrup strength.", "GI"),
    "ORS": _d(0, 0, 0, 0, 0, 1, ["PO"],
        "Give small sips often after each loose stool/vomit as advised. Use clean water to mix.",
        "Volume-based (ml/kg), not mg/kg. Follow diarrhea plan.", "GI"),
    "ZINC_SULPHATE": _d(1, 2, 20, 2, 20, 1, ["PO"],
        "Give by mouth once daily for 10–14 days in diarrhea protocols as advised.",
        "Age-banded (10–20 mg elemental zinc daily).", "GI"),
    "ONDANSETRON_ODT": _d(0.1, 0.15, 8, 0.45, 24, 3, ["PO"],
        "Place tablet on tongue to dissolve; no water needed.",
        "Same mg/kg as ondansetron.", "Antiemetic"),

    # --- Respiratory ---
    "SALBUTAMOL": _d(0.1, 0.15, 4, 0.6, 16, 4, ["Inhalation", "PO", "IV"],
        "Prefer inhaler/nebulizer with spacer. Shake inhaler; breathe slowly. Oral syrup only if prescribed.",
        "Inhaled dosing device-based; oral ~0.1–0.15 mg/kg/dose.", "Respiratory"),
    "ALBUTEROL": _d(0.1, 0.15, 4, 0.6, 16, 4, ["Inhalation", "PO"],
        "Same as salbutamol — use spacer for inhaler.",
        "Device-based nebulizer/MDI dosing preferred.", "Respiratory"),
    "BUDESONIDE_NEB": _d(0.25, 0.5, 1, 1, 2, 2, ["Inhalation"],
        "Nebulize as prescribed. Rinse mouth after steroid inhalation if possible.",
        "Nebule strengths 0.25–0.5 mg; not classic mg/kg.", "Respiratory"),
    "PREDNISOLONE": _d(1, 2, 60, 2, 80, 1, ["PO"],
        "Give by mouth with food in morning if once daily. Do not stop suddenly after long courses.",
        "1–2 mg/kg/day (asthma exacerbations often 1–2 mg/kg/day short course).", "Steroid"),
    "PREDNISONE": _d(1, 2, 60, 2, 80, 1, ["PO"],
        "Give by mouth with food.",
        "Similar to prednisolone.", "Steroid"),
    "DEXAMETHASONE": _d(0.15, 0.6, 16, 0.6, 16, 1, ["PO", "IV", "IM"],
        "Single or short course as prescribed (croup often one dose).",
        "Croup often 0.15–0.6 mg/kg once.", "Steroid"),
    "HYDROCORTISONE": _d(1, 2, 100, 8, 400, 4, ["IV", "PO", "IM"],
        "Hospital dosing common for stress/allergy.",
        "Indication-specific (e.g., 1–2 mg/kg/dose).", "Steroid"),
    "MONTELUKAST": _d(0.1, 0.2, 10, 0.2, 10, 1, ["PO"],
        "Give by mouth once daily evening. Age-banded chew/granules.",
        "Age-banded (4–10 mg), not strictly mg/kg.", "Respiratory"),
    "IPRATROPIUM": _d(0, 0, 0.5, 0, 1.5, 3, ["Inhalation"],
        "Nebulizer/inhaler as prescribed with salbutamol sometimes.",
        "Device dose (nebules), not mg/kg.", "Respiratory"),

    # --- Anticonvulsant / Neuro ---
    "DIAZEPAM": _d(0.1, 0.3, 10, 0.6, 20, 2, ["IV", "PR", "PO"],
        "Emergency seizure medicine — follow rescue plan. Rectal/IV per training.",
        "PR/IV rescue ~0.2–0.5 mg/kg (protocol-specific).", "Neuro"),
    "MIDAZOLAM": _d(0.1, 0.2, 10, 0.4, 20, 1, ["IV", "IM", "Buccal", "IN"],
        "Emergency use per seizure action plan.",
        "Buccal/IN/IV doses protocol-specific.", "Neuro"),
    "LEVETIRACETAM": _d(10, 20, 1500, 60, 3000, 2, ["PO", "IV"],
        "Give by mouth twice daily regularly. Do not miss doses.",
        "Start ~20–40 mg/kg/day ÷ BID; titrate.", "Neuro"),
    "VALPROATE": _d(10, 15, 1000, 60, 3000, 2, ["PO", "IV"],
        "Give by mouth with food. Regular timing important.",
        "Start ~10–15 mg/kg/day; usual maintenance higher with levels.", "Neuro"),
    "PHENYTOIN": _d(2, 2.5, 100, 10, 300, 2, ["PO", "IV"],
        "Give consistently with/without food as advised. IV hospital only.",
        "Maintenance ~5–10 mg/kg/day; loading separate.", "Neuro"),
    "PHENOBARBITAL": _d(3, 5, 100, 6, 200, 1, ["PO", "IV", "IM"],
        "Give at same time daily. Causes sleepiness.",
        "Maintenance ~3–6 mg/kg/day.", "Neuro"),
    "CARBAMAZEPINE": _d(5, 10, 400, 30, 1600, 2, ["PO"],
        "Give by mouth with food. Do not stop suddenly.",
        "Start low; maintenance often 10–30 mg/kg/day ÷ BID–TID.", "Neuro"),

    # --- Vitamins / Others common ---
    "VITAMIN_D3": _d(0, 0, 60000, 0, 60000, 1, ["PO"],
        "Drops/tablets by mouth as prescribed (daily or weekly regimens differ).",
        "IU-based, not mg/kg. Follow labeled IU dose.", "Supplement"),
    "IRON_SYRUP": _d(1, 2, 65, 6, 200, 1, ["PO"],
        "Give by mouth between meals if tolerated; vitamin C food may help. May darken stools.",
        "Elemental iron ~3–6 mg/kg/day for deficiency treatment.", "Supplement"),
    "CALCIUM": _d(20, 40, 500, 80, 1500, 2, ["PO", "IV"],
        "Oral with food unless told otherwise. IV only in hospital.",
        "Elemental calcium dosing indication-specific.", "Supplement"),
    "FOLIC_ACID": _d(0.025, 0.05, 5, 0.05, 5, 1, ["PO"],
        "Give by mouth once daily.",
        "Age/indication based (often 1–5 mg).", "Supplement"),
    "MULTIVITAMIN": _d(0, 0, 0, 0, 0, 1, ["PO"],
        "Give by mouth once daily with food as labeled for age.",
        "Age-banded drops/syrup; not mg/kg.", "Supplement"),
    "ADRENALINE": _d(0.01, 0.01, 0.5, 0.03, 1.5, 1, ["IM", "IV", "SC"],
        "Emergency IM into thigh for anaphylaxis per weight device/plan.",
        "IM anaphylaxis 0.01 mg/kg (1:1000); max 0.3–0.5 mg.", "Emergency"),
    "ATROPINE": _d(0.01, 0.02, 0.5, 0.04, 1, 1, ["IV", "IM"],
        "Hospital emergency medicine.",
        "0.01–0.02 mg/kg/dose IV.", "Emergency"),
    "HYDROCORTISONE_TOPICAL": _d(0, 0, 0, 0, 0, 2, ["Topical"],
        "Apply thin layer to affected skin only. Avoid eyes/mouth.",
        "Topical; not mg/kg systemic calc.", "Dermatology"),
    "MUPIROCIN": _d(0, 0, 0, 0, 0, 3, ["Topical"],
        "Apply thin layer to skin infection area 2–3 times daily.",
        "Topical antibiotic ointment.", "Dermatology"),
    "CLOTRIMAZOLE": _d(0, 0, 0, 0, 0, 2, ["Topical", "PO"],
        "Cream: apply thin layer. Oral lozenges only if prescribed.",
        "Topical antifungal.", "Antifungal"),
    "FLUCONAZOLE": _d(3, 6, 400, 12, 800, 1, ["PO", "IV"],
        "Give by mouth once daily. Finish course.",
        "3–6 mg/kg/day (loading sometimes used).", "Antifungal"),
    "NYSTATIN": _d(0, 0, 0, 0, 0, 4, ["PO", "Topical"],
        "Oral suspension: place in mouth, keep as long as possible, then swallow.",
        "Unit/ml dosing, not mg/kg.", "Antifungal"),
    "ACYCLOVIR": _d(10, 20, 800, 80, 3200, 4, ["PO", "IV"],
        "Give by mouth 4–5 times daily with water. Start early for best effect.",
        "PO often 20 mg/kg/dose QID (indication-specific); IV different.", "Antiviral"),
    "OSELTAMIVIR": _d(2, 3, 75, 6, 150, 2, ["PO"],
        "Give by mouth twice daily for 5 days (treatment) as age/weight band.",
        "Weight-banded capsules/suspension.", "Antiviral"),
    "ALBENDAZOLE": _d(7.5, 7.5, 400, 15, 400, 1, ["PO"],
        "Give by mouth with food. Single or short course as advised.",
        "Often 400 mg single (age/weight rules).", "Anthelmintic"),
    "MEBENDAZOLE": _d(0, 0, 100, 0, 200, 2, ["PO"],
        "Give by mouth as single or BD course per worm type.",
        "Age-banded tablet dosing.", "Anthelmintic"),
    "DIETHYLCARBAMAZINE": _d(1, 2, 100, 6, 300, 3, ["PO"],
        "Give by mouth after food as course prescribed.",
        "Specialist protocols for filaria.", "Anthelmintic"),
    "CHLOROQUINE": _d(5, 5, 300, 10, 500, 1, ["PO"],
        "Give by mouth with food. Exact malaria regimen must be followed.",
        "Base mg/kg malaria regimens — confirm species/resistance.", "Antimalarial"),
    "ARTESUNATE": _d(2.4, 2.4, 120, 7.2, 360, 3, ["IV", "IM"],
        "Hospital severe malaria protocol.",
        "2.4 mg/kg/dose at 0, 12, 24 hr then daily.", "Antimalarial"),
    "PRIMEQUINE": _d(0.25, 0.5, 15, 0.5, 30, 1, ["PO"],
        "Give by mouth with food after G6PD status known.",
        "Indication/species specific.", "Antimalarial"),
    "ISONIAZID": _d(10, 15, 300, 15, 300, 1, ["PO"],
        "Give by mouth once daily on empty stomach if tolerated.",
        "10–15 mg/kg/day (max 300 mg) for TB regimens.", "Anti-TB"),
    "RIFAMPICIN": _d(10, 20, 600, 20, 600, 1, ["PO", "IV"],
        "Give by mouth once daily empty stomach. Turns body fluids orange.",
        "10–20 mg/kg/day.", "Anti-TB"),
    "PYRAZINAMIDE": _d(30, 40, 2000, 40, 2000, 1, ["PO"],
        "Give by mouth once daily as part of TB regimen.",
        "30–40 mg/kg/day.", "Anti-TB"),
    "ETHAMBUTOL": _d(15, 25, 1600, 25, 1600, 1, ["PO"],
        "Give by mouth once daily. Report vision changes.",
        "15–25 mg/kg/day.", "Anti-TB"),
    "INSULIN_REGULAR": _d(0, 0, 0, 0, 0, 1, ["SC", "IV"],
        "Inject subcutaneously as diabetes plan. Rotate sites. Never share pens/needles.",
        "Units/kg — individualized insulin plan required.", "Endocrine"),
    "THYROXINE": _d(0.002, 0.005, 0.2, 0.005, 0.2, 1, ["PO"],
        "Give by mouth every morning on empty stomach with water.",
        "Age-based mcg/kg/day; lab-titrated.", "Endocrine"),
    "SYRUP_OF_IPECA": _d(0, 0, 0, 0, 0, 1, ["PO"],
        "NOT recommended for home poisoning. Seek emergency care.",
        "Do not use for routine poisoning first aid.", "Toxicology"),
}

# Fix typo key if present
if "OMEPRRAZOLE" in PEDIATRIC_DRUG_DB:
    PEDIATRIC_DRUG_DB.pop("OMEPRRAZOLE", None)


# --- Common OPD symptom drugs (cold, cough, fever, pain, vomit, allergy, scabies) ---
_OPD = {
    "PHENYLEPHRINE": _d(0.1, 0.15, 10, 0.6, 40, 4, ["PO"],
        "Give by mouth as labeled for age. Short courses only.",
        "Nasal congestion; limited pediatric evidence. Prefer saline first.", "OPD-Cold",
        "Infants <2 yr (many products); severe hypertension; MAOI use.",
        "Common cold nasal congestion"),
    "PSEUDOEPHEDRINE": _d(1, 1, 60, 4, 240, 4, ["PO"],
        "Give by mouth. Avoid evening dose if sleeplessness.",
        "Decongestant; age restrictions apply on many OTC labels.", "OPD-Cold",
        "Young children per OTC label; severe HTN; MAOI.",
        "Nasal congestion"),
    "XYLOMETAZOLINE_NASAL": _d(0, 0, 0, 0, 0, 2, ["Nasal"],
        "1–2 drops/sprays per nostril as labeled. Max 3–5 days to avoid rebound congestion.",
        "Topical nasal decongestant; not mg/kg.", "OPD-Cold",
        "Infants (product-specific); prolonged use >5 days.",
        "Blocked nose"),
    "NORMAL_SALINE_NASAL": _d(0, 0, 0, 0, 0, 4, ["Nasal"],
        "2–3 drops each nostril as needed. Safe first-line for cold.",
        "Supportive care for rhinitis.", "OPD-Cold",
        "None significant.",
        "Common cold / nasal block"),
    "DEXTROMETHORPHAN": _d(0.2, 0.25, 30, 1, 120, 4, ["PO"],
        "Give by mouth for dry cough. Do not combine multiple cough syrups.",
        "Antitussive for dry cough; avoid in productive cough needing clearance.", "OPD-Cough",
        "Children <4–6 yr for many OTC products; MAOI use.",
        "Dry cough"),
    "AMBROXOL": _d(0.3, 0.5, 30, 1.5, 90, 3, ["PO"],
        "Give by mouth after food. Encourage fluids.",
        "Mucolytic for productive cough.", "OPD-Cough",
        "Known hypersensitivity; caution in severe hepatic disease.",
        "Productive cough"),
    "GUAIFENESIN": _d(2, 3, 200, 12, 1200, 4, ["PO"],
        "Give by mouth with plenty of water.",
        "Expectorant; hydrate well.", "OPD-Cough",
        "OTC age limits; hypersensitivity.",
        "Productive cough"),
    "BROMHEXINE": _d(0.2, 0.3, 8, 0.9, 24, 3, ["PO"],
        "Give by mouth after food.",
        "Mucolytic.", "OPD-Cough",
        "Hypersensitivity; caution peptic ulcer.",
        "Productive cough"),
    "ACETYLCYSTEINE_ORAL": _d(5, 10, 600, 30, 1200, 2, ["PO"],
        "Give by mouth diluted as advised. Distinct from IV antidote dosing.",
        "Mucolytic oral use.", "OPD-Cough",
        "Hypersensitivity; caution asthma (bronchospasm risk).",
        "Thick secretions"),
    "HONEY_COUGH": _d(0, 0, 0, 0, 0, 3, ["PO"],
        "1/2–1 tsp honey for cough in children >1 year. Not for infants.",
        "Supportive antitussive.", "OPD-Cough",
        "Age <1 year (botulism risk).",
        "Cough >1 year age"),
    "HYOSCINE_BUTYLBROMIDE": _d(0.3, 0.5, 10, 1.5, 30, 3, ["PO", "IV", "IM"],
        "Give by mouth for colicky abdominal pain as prescribed.",
        "Antispasmodic for abdominal colic.", "OPD-Abdomen",
        "Myasthenia gravis; megacolon; glaucoma caution; hypersensitivity.",
        "Colicky abdominal pain"),
    "DROTAVERINE": _d(1, 1.5, 80, 6, 240, 3, ["PO", "IV"],
        "Give by mouth for abdominal cramps as prescribed.",
        "Antispasmodic used in some regions.", "OPD-Abdomen",
        "Severe hepatic/renal/cardiac failure; hypersensitivity.",
        "Abdominal cramps"),
    "SIMETHICONE": _d(0, 0, 40, 0, 160, 4, ["PO"],
        "Give by mouth after feeds for gas/colic. Shake drops.",
        "Anti-foaming agent for gas pain; dose often drops by age.", "OPD-Abdomen",
        "Hypersensitivity.",
        "Gas / infantile colic supportive"),
    "ORAL_REHYDRATION_SALTS": _d(0, 0, 0, 0, 0, 1, ["PO"],
        "Give small frequent sips after each loose stool. Mix packet with clean water only.",
        "WHO ORS for diarrhea/vomiting dehydration prevention.", "OPD-GI",
        "Severe persistent vomiting with inability to drink — needs IV assessment.",
        "Diarrhea / mild dehydration"),
    "ZINC_ACETATE": _d(0, 0, 20, 0, 20, 1, ["PO"],
        "Give by mouth once daily for 10–14 days with diarrhea protocol.",
        "Age-banded elemental zinc 10–20 mg/day.", "OPD-GI",
        "Copper deficiency with prolonged high-dose use.",
        "Acute diarrhea adjunct"),
    "RACECADOTRIL": _d(1.5, 1.5, 100, 4.5, 300, 3, ["PO"],
        "Give by mouth with ORS for watery diarrhea as prescribed.",
        "Antisecretory antidiarrheal.", "OPD-GI",
        "Fructose intolerance (some sachets); hypersensitivity.",
        "Watery diarrhea"),
    "PROBIOTIC_SACHET": _d(0, 0, 0, 0, 0, 1, ["PO"],
        "Give by mouth once/twice daily mixed in cool water/milk as labeled.",
        "Adjunct in diarrhea; strain-specific.", "OPD-GI",
        "Severely immunocompromised (rare invasive risk with some strains).",
        "Diarrhea adjunct"),
    "MEFENAMIC_ACID": _d(6, 6.5, 500, 25, 1500, 3, ["PO"],
        "Give by mouth after food for short courses of pain/fever if prescribed.",
        "NSAID; prefer paracetamol/ibuprofen first in children.", "OPD-Fever",
        "PUD; dehydration/renal impairment; NSAID allergy; often avoided in young children.",
        "Pain / fever older children"),
    "CETIRIZINE_DROPS": _d(0.25, 0.25, 10, 0.25, 10, 1, ["PO"],
        "Give by mouth once daily for allergy/rash/itch.",
        "Same as cetirizine; drops useful in toddlers.", "OPD-Allergy",
        "Severe renal impairment (dose adjust); hypersensitivity.",
        "Allergic rhinitis / urticaria"),
    "CALAMINE_LOTION": _d(0, 0, 0, 0, 0, 3, ["Topical"],
        "Apply thin layer on itchy rash; avoid eyes/mouth.",
        "Soothing topical for itch.", "OPD-Allergy",
        "Open infected wounds; hypersensitivity.",
        "Itchy rash"),
    "HYDROCORTISONE_1_CREAM": _d(0, 0, 0, 0, 0, 2, ["Topical"],
        "Apply thin layer 1–2 times daily to affected skin for short course.",
        "Mild topical steroid for allergic dermatitis.", "OPD-Allergy",
        "Untreated skin infection; face/groin prolonged use without advice.",
        "Allergic dermatitis"),
    "PERMETHRIN_5_CREAM": _d(0, 0, 0, 0, 0, 1, ["Topical"],
        "Apply neck-to-toe (include head in infants). Wash after 8–14 hours. Often repeat after 7 days. Wash clothes/bedding.",
        "First-line scabies treatment.", "OPD-Scabies",
        "Hypersensitivity to permethrin/chrysanthemums.",
        "Scabies"),
    "PERMETHRIN_1_RINSE": _d(0, 0, 0, 0, 0, 1, ["Topical"],
        "Head lice: apply to hair per label, rinse, comb nits. May repeat day 9.",
        "Pediculosis.", "OPD-Scabies",
        "Hypersensitivity.",
        "Head lice"),
    "IVERMECTIN_ORAL": _d(0.2, 0.2, 15, 0.2, 15, 1, ["PO"],
        "Single oral dose as specialist advises (often empty stomach). May repeat in 7–14 days.",
        "200 mcg/kg for selected/crusted scabies.", "OPD-Scabies",
        "Children <15 kg/<5 yr often avoided; pregnancy caution.",
        "Scabies (selected)"),
    "SULFUR_OINTMENT": _d(0, 0, 0, 0, 0, 1, ["Topical"],
        "Apply as directed for several nights; useful infant/pregnancy alternative.",
        "Alternative scabicide.", "OPD-Scabies",
        "Sulfur allergy; irritation.",
        "Scabies alternative"),
    "BENZYL_BENZOATE": _d(0, 0, 0, 0, 0, 1, ["Topical"],
        "Apply as labeled; can irritate — dilute for children if advised.",
        "Older scabies lotion.", "OPD-Scabies",
        "Broken skin; infants (irritation).",
        "Scabies (resource-limited)"),
    "LINDANE": _d(0, 0, 0, 0, 0, 1, ["Topical"],
        "Generally avoided in children — prefer permethrin.",
        "Neurotoxicity risk.", "OPD-Scabies",
        "Children, pregnancy, seizures, broken skin — AVOID.",
        "Historical scabies — avoid"),
    "FUSIDIC_ACID_CREAM": _d(0, 0, 0, 0, 0, 3, ["Topical"],
        "Apply thin layer 2–3 times daily to infected skin.",
        "Topical antibiotic for impetigo/infected rash.", "OPD-Skin",
        "Hypersensitivity.",
        "Impetigo / infected eczema"),
    "ANTACID_SYRUP": _d(0, 0, 0, 0, 0, 3, ["PO"],
        "Give by mouth after meals for dyspepsia as labeled by age.",
        "Symptomatic acid relief; volume/age based.", "OPD-Abdomen",
        "Severe renal failure (Mg/Al content); suspected surgical abdomen.",
        "Dyspepsia"),
    "PARACETAMOL_DROPS": _d(10, 15, 1000, 90, 4000, 4, ["PO"],
        "Use dropper carefully. 10–15 mg/kg every 4–6 hours.",
        "Fever/pain first-line.", "OPD-Fever",
        "Severe liver disease; chronic overdose risk.",
        "Fever / pain"),
    "IBUPROFEN_SUSPENSION": _d(5, 10, 800, 40, 2400, 3, ["PO"],
        "Give after food. Avoid if dehydrated / poor intake.",
        "Fever/pain NSAID.", "OPD-Fever",
        "Dehydration; renal disease; active ulcer; NSAID allergy; often avoid <6 months.",
        "Fever / pain"),
    "ONDANSETRON_SYRUP": _d(0.1, 0.15, 8, 0.45, 24, 3, ["PO"],
        "Give by mouth for vomiting as prescribed.",
        "Antiemetic.", "OPD-Vomit",
        "Congenital long QT; QT-prolonging drugs caution.",
        "Acute vomiting"),
    "DOMPERIDONE_SUSPENSION": _d(0.25, 0.5, 10, 1.2, 30, 3, ["PO"],
        "Give before meals; short course only.",
        "Antiemetic/prokinetic.", "OPD-Vomit",
        "Cardiac arrhythmia/QT risk; avoid prolonged OPD use.",
        "Nausea / vomiting"),
    "MENTHOL_LOZENGE": _d(0, 0, 0, 0, 0, 4, ["PO"],
        "Dissolve in mouth for throat irritation (older children who can suck safely).",
        "Supportive sore throat/cough.", "OPD-Cold",
        "Age with choking risk (young children).",
        "Sore throat / cough"),
    "CHLORPHENIRAMINE_SYRUP": _d(0.1, 0.2, 4, 0.35, 24, 3, ["PO"],
        "Give by mouth. Causes sleepiness — caution.",
        "Sedating antihistamine for allergy/cold symptomatic.", "OPD-Allergy",
        "Neonates; caution with other sedatives; MAOI.",
        "Allergic rhinitis / itch"),
}

PEDIATRIC_DRUG_DB.update(_OPD)

_UPDATES = {
    "AMOXICILLIN": {
        "min_mg_kg": 13.0, "max_mg_kg": 30.0, "max_daily_mg_kg": 90.0,
        "absolute_max_daily_mg": 3000.0, "default_doses_per_day": 2,
        "notes": "Mild-moderate 40–50 mg/kg/day ÷ Q8–12h; high-dose AOM/CAP 80–90 mg/kg/day ÷ Q12h. Max 2–3 g/day.",
        "contraindications": "Hypersensitivity to penicillins.",
        "indications": "AOM, CAP, pharyngitis, SSTI",
    },
    "AMOXICILLIN-CLAVULANATE": {
        "notes": "Standard 45 mg/kg/day ÷ Q12h; high-dose 90 mg/kg/day ÷ Q12h (amoxicillin component). Max ~4 g amoxicillin/day.",
        "contraindications": "Prior cholestatic jaundice with Augmentin; severe penicillin allergy.",
        "indications": "AOM, sinusitis, bites, CAP",
    },
    "CEFTRIAXONE": {
        "contraindications": "Neonates <28 days (biliary sludging/kernicterus risk). Severe cephalosporin allergy.",
        "indications": "Severe AOM, CAP, UTI, meningitis",
    },
    "COTRIMOXAZOLE": {
        "contraindications": "Neonates <2 months (kernicterus); severe sulfa allergy.",
        "indications": "SSTI/MRSA, UTI, PCP",
    },
    "NITROFURANTOIN": {
        "contraindications": "Infants <2 months; significant renal impairment; near-term pregnancy.",
        "indications": "UTI / prophylaxis",
    },
    "AZITHROMYCIN": {
        "contraindications": "Prior cholestatic jaundice with azithromycin; caution QT prolongation.",
        "indications": "AOM, atypical CAP, pharyngitis (PCN allergy)",
    },
    "CETIRIZINE": {
        "contraindications": "Severe renal impairment (adjust/avoid); hypersensitivity.",
        "indications": "Allergic rhinitis, urticaria, allergic rash",
    },
    "ONDANSETRON": {
        "contraindications": "Congenital long-QT syndrome; caution with other QT drugs.",
        "indications": "Vomiting",
    },
    "OMEPRAZOLE": {
        "contraindications": "Hypersensitivity to PPIs; caution severe liver disease.",
        "indications": "GERD, gastritis, abdominal dyspepsia",
    },
    "IBUPROFEN": {
        "contraindications": "Dehydration, renal impairment, active GI bleed/ulcer, NSAID allergy; often avoid <6 months.",
        "indications": "Fever, pain, inflammation",
    },
    "PARACETAMOL": {
        "contraindications": "Severe hepatic impairment; chronic overdose risk.",
        "indications": "Fever, pain",
    },
    "PROMETHAZINE": {
        "contraindications": "Children <2 years for cough/cold; phenothiazine allergy.",
        "indications": "Allergy/nausea (specialist caution)",
    },
}

for k, upd in _UPDATES.items():
    if k in PEDIATRIC_DRUG_DB:
        PEDIATRIC_DRUG_DB[k].update(upd)

for k, v in PEDIATRIC_DRUG_DB.items():
    v.setdefault("contraindications", "Hypersensitivity to drug class; confirm age/organ function before use.")
    v.setdefault("indications", v.get("category", "Pediatric use"))


def list_drugs_by_category():
    cats = {}
    for name, meta in PEDIATRIC_DRUG_DB.items():
        cats.setdefault(meta.get("category", "General"), []).append(name)
    for k in cats:
        cats[k] = sorted(cats[k])
    return cats

def calculate_pediatric_dose(drug_name, weight_kg, mg_per_kg=None, doses_per_day=None, route=None):
    key = drug_name.strip().upper()
    if key not in PEDIATRIC_DRUG_DB:
        return {"ok": False, "message": f"Drug '{drug_name}' not in database."}
    rules = PEDIATRIC_DRUG_DB[key]
    if weight_kg <= 0:
        return {"ok": False, "message": "Weight must be > 0."}

    use_mg_kg = rules["min_mg_kg"] if mg_per_kg is None else float(mg_per_kg)
    freq = rules["default_doses_per_day"] if doses_per_day is None else int(doses_per_day)
    routes = rules.get("routes", [])
    chosen_route = route if route in routes else (routes[0] if routes else "PO")

    # Non mg/kg products
    if rules["min_mg_kg"] == 0 and rules["max_mg_kg"] == 0 and rules["absolute_max_single_mg"] == 0:
        return {
            "ok": True,
            "drug": key,
            "weight_kg": weight_kg,
            "mg_per_kg": None,
            "single_dose_mg": None,
            "daily_dose_mg": None,
            "suggested_min_mg": None,
            "suggested_max_mg": None,
            "doses_per_day": freq,
            "route": chosen_route,
            "routes": routes,
            "how_to_take": rules.get("how_to_take", ""),
            "notes": rules.get("notes", ""),
            "message": "This medicine is age/device/volume based — see notes (not calculated as mg/kg × weight).",
        }

    single = round(use_mg_kg * weight_kg, 1)
    single = min(single, rules["absolute_max_single_mg"])
    daily = round(single * freq, 1)
    max_daily = min(rules["max_daily_mg_kg"] * weight_kg, rules["absolute_max_daily_mg"])
    sug_min = round(rules["min_mg_kg"] * weight_kg, 1)
    sug_max = round(min(rules["max_mg_kg"] * weight_kg, rules["absolute_max_single_mg"]), 1)

    warn = ""
    if daily > max_daily:
        warn = f" Warning: calculated daily {daily} mg exceeds usual max ~{round(max_daily, 1)} mg/day."
    if use_mg_kg < rules["min_mg_kg"] or use_mg_kg > rules["max_mg_kg"]:
        warn += f" Note: mg/kg ({use_mg_kg}) is outside usual Harriet Lane–aligned range {rules['min_mg_kg']}–{rules['max_mg_kg']}."

    return {
        "ok": True,
        "drug": key,
        "weight_kg": weight_kg,
        "mg_per_kg": use_mg_kg,
        "single_dose_mg": single,
        "daily_dose_mg": daily,
        "suggested_min_mg": sug_min,
        "suggested_max_mg": sug_max,
        "hl_min_mg_kg": rules["min_mg_kg"],
        "hl_max_mg_kg": rules["max_mg_kg"],
        "doses_per_day": freq,
        "route": chosen_route,
        "routes": routes,
        "how_to_take": rules.get("how_to_take", ""),
        "notes": rules.get("notes", ""),
        "message": f"Exact single dose: {single} mg via {chosen_route}." + warn,
    }
