import type { DrugRecord, PracticalInteraction } from "./types";

export const KNOWN_CONDITIONS = [
  "Heart Failure",
  "CKD",
  "Diabetes",
  "Hypertension",
  "Atrial Fibrillation",
  "CAD / ACS",
  "COPD",
  "Peptic Ulcer Disease",
  "Fall Risk / Frailty",
  "Depression",
  "Infection / Sepsis",
  "Asthma",
  "Hypothyroidism",
  "Osteoporosis",
  "Anemia",
] as const;

export const drugsDB: DrugRecord[] = [
  // —— Analgesics / antipyretics / NSAIDs ——
  {
    id: "paracetamol",
    name: "Paracetamol (Acetaminophen / Crocin / Dolo)",
    class: "Analgesic / antipyretic",
    standardDose: "500–1000 mg PO q6–8h (max 3–4 g/day adult)",
    pediatricDoseRule: "Paracetamol: 10–15 mg/kg/dose PO q4–6h",
    pediatricMgPerKgDay: 12.5,
    pediatricDoseUnit: "mg/kg/dose",
    renalAdjustmentLimit: 30,
    renalNote: "Use cautiously in advanced CKD; avoid chronic high doses.",
  },
  {
    id: "ibuprofen",
    name: "Ibuprofen (Brufen / Combiflam component)",
    class: "NSAID",
    standardDose: "200–400 mg PO q6–8h with food",
    pediatricDoseRule: "Ibuprofen: 5–10 mg/kg/dose PO q6–8h",
    pediatricMgPerKgDay: 20,
    pediatricDoseUnit: "mg/kg/day",
    renalAdjustmentLimit: 60,
    renalNote: "Avoid or use short course in CKD; risk of AKI and fluid retention.",
    geriatricGuidelines: [
      {
        type: "Beers",
        ruleDescription: "NSAIDs increase GI bleed, AKI, HF exacerbation risk in older adults.",
        recommendation: "Avoid chronic use; prefer paracetamol when possible",
      },
    ],
  },
  {
    id: "diclofenac",
    name: "Diclofenac (Voveran / Dynapar)",
    class: "NSAID",
    standardDose: "50 mg PO BID–TID with food (short course)",
    renalAdjustmentLimit: 60,
    renalNote: "Avoid in significant CKD; CV and GI risk.",
    geriatricGuidelines: [
      {
        type: "Beers",
        ruleDescription: "Systemic NSAIDs — GI, renal, CV risk in elderly.",
        recommendation: "Avoid prolonged use",
      },
    ],
  },
  {
    id: "aspirin",
    name: "Aspirin (Ecosprin / ASA)",
    class: "Antiplatelet / NSAID",
    standardDose: "75–150 mg PO daily (antiplatelet); higher for analgesia short-term",
  },
  {
    id: "tramadol",
    name: "Tramadol (Tramazac / Ultracet combo)",
    class: "Weak opioid analgesic",
    standardDose: "50–100 mg PO q6–8h PRN (max per label)",
    renalAdjustmentLimit: 30,
    renalNote: "Extend interval in CKD; seizure and serotonin risk.",
    geriatricGuidelines: [
      {
        type: "Beers",
        ruleDescription: "Opioids increase fall, delirium, constipation risk.",
        recommendation: "Use lowest effective dose; monitor",
      },
    ],
  },

  // —— Antibiotics (commonly prescribed) ——
  {
    id: "amoxicillin",
    name: "Amoxicillin (Mox / Novamox)",
    class: "Penicillin antibiotic",
    standardDose: "250–500 mg PO TID (adult); higher for some RTI",
    pediatricDoseRule: "Amoxicillin: 40–90 mg/kg/day PO divided q8–12h",
    pediatricMgPerKgDay: 45,
    pediatricDoseUnit: "mg/kg/day",
    renalAdjustmentLimit: 30,
    renalNote: "Extend dosing interval in severe renal impairment.",
  },
  {
    id: "amoxicillin-clavulanate",
    name: "Amoxicillin-Clavulanate (Amoxyclav / Augmentin / Clavam / Moxclav)",
    class: "Penicillin + beta-lactamase inhibitor",
    standardDose: "625 mg PO BID–TID or 1 g PO BID (adult; product-specific)",
    pediatricDoseRule:
      "Amox-clav: often 45 mg/kg/day (amox component) ÷ BID; high-dose 90 mg/kg/day for AOM (7:1 / 14:1)",
    pediatricMgPerKgDay: 45,
    pediatricDoseUnit: "mg/kg/day",
    renalAdjustmentLimit: 30,
    renalNote: "Adjust interval in severe CKD; watch for diarrhoea / cholestatic hepatitis.",
  },
  {
    id: "azithromycin",
    name: "Azithromycin (Azithral / Azee / Zithromax)",
    class: "Macrolide antibiotic",
    standardDose: "500 mg PO day 1 then 250 mg daily × 4 days, or 500 mg daily × 3 days",
    pediatricDoseRule: "Azithromycin: often 10 mg/kg day 1 then 5 mg/kg days 2–5 (regimen varies)",
    pediatricMgPerKgDay: 10,
    pediatricDoseUnit: "mg/kg/day",
  },
  {
    id: "clarithromycin",
    name: "Clarithromycin (Klaricid / Claribid)",
    class: "Macrolide antibiotic",
    standardDose: "250–500 mg PO BID",
    renalAdjustmentLimit: 30,
    renalNote: "Dose-adjust in significant renal impairment; many CYP3A4 interactions.",
  },
  {
    id: "erythromycin",
    name: "Erythromycin",
    class: "Macrolide antibiotic",
    standardDose: "250–500 mg PO QID (formulation-dependent)",
    geriatricGuidelines: [
      {
        type: "Beers",
        ruleDescription: "Macrolides (esp. erythromycin) — QT and interaction risk.",
        recommendation: "Use with caution; check interactions",
      },
    ],
  },
  {
    id: "cefixime",
    name: "Cefixime (Taxim-O / Zifi)",
    class: "3rd-generation cephalosporin",
    standardDose: "200–400 mg PO daily (adult)",
    pediatricDoseRule: "Cefixime: 8 mg/kg/day PO (single or BID)",
    pediatricMgPerKgDay: 8,
    pediatricDoseUnit: "mg/kg/day",
    renalAdjustmentLimit: 60,
    renalNote: "Extend interval or reduce dose when CrCl falls.",
  },
  {
    id: "cefpodoxime",
    name: "Cefpodoxime (Cefoprox / Gudcef)",
    class: "3rd-generation cephalosporin",
    standardDose: "100–200 mg PO BID",
    pediatricDoseRule: "Cefpodoxime: ~10 mg/kg/day ÷ BID",
    pediatricMgPerKgDay: 10,
    pediatricDoseUnit: "mg/kg/day",
    renalAdjustmentLimit: 30,
    renalNote: "Extend interval in severe renal impairment.",
  },
  {
    id: "cefuroxime",
    name: "Cefuroxime (Zinnat / Ceftum)",
    class: "2nd-generation cephalosporin",
    standardDose: "250–500 mg PO BID",
    pediatricDoseRule: "Cefuroxime axetil: often 20–30 mg/kg/day ÷ BID",
    pediatricMgPerKgDay: 25,
    pediatricDoseUnit: "mg/kg/day",
    renalAdjustmentLimit: 30,
    renalNote: "Adjust in significant CKD.",
  },
  {
    id: "ceftriaxone",
    name: "Ceftriaxone (Monocef / Rocephin)",
    class: "3rd-generation cephalosporin",
    standardDose: "1–2 g IV/IM once daily (up to 2 g BID for severe)",
    pediatricDoseRule: "Ceftriaxone: 50–100 mg/kg/day IV/IM (max often 2–4 g/day)",
    pediatricMgPerKgDay: 75,
    pediatricDoseUnit: "mg/kg/day",
  },
  {
    id: "cefalexin",
    name: "Cefalexin / Cephalexin (Phexin / Sporidex)",
    class: "1st-generation cephalosporin",
    standardDose: "250–500 mg PO QID",
    pediatricDoseRule: "Cephalexin: 25–50 mg/kg/day ÷ TID–QID",
    pediatricMgPerKgDay: 40,
    pediatricDoseUnit: "mg/kg/day",
    renalAdjustmentLimit: 50,
    renalNote: "Extend interval in renal impairment.",
  },
  {
    id: "ciprofloxacin",
    name: "Ciprofloxacin (Ciplox / Cifran)",
    class: "Fluoroquinolone",
    standardDose: "250–750 mg PO BID",
    renalAdjustmentLimit: 50,
    renalNote: "Reduce dose / extend interval when CrCl < 50 mL/min.",
    geriatricGuidelines: [
      {
        type: "Beers",
        ruleDescription: "Fluoroquinolones — tendon, CNS, hypoglycaemia, aortic risk signals.",
        recommendation: "Reserve for when alternatives unsuitable",
      },
    ],
  },
  {
    id: "levofloxacin",
    name: "Levofloxacin (Levoflox / Tavanic)",
    class: "Fluoroquinolone",
    standardDose: "500–750 mg PO/IV daily",
    renalAdjustmentLimit: 50,
    renalNote: "Dose-adjust in CKD; QT and tendon risk.",
  },
  {
    id: "ofloxacin",
    name: "Ofloxacin (Zanocin / Oflox)",
    class: "Fluoroquinolone",
    standardDose: "200–400 mg PO BID",
    renalAdjustmentLimit: 50,
    renalNote: "Adjust in renal impairment.",
  },
  {
    id: "norfloxacin",
    name: "Norfloxacin (Norflox)",
    class: "Fluoroquinolone",
    standardDose: "400 mg PO BID (often UTI)",
    renalAdjustmentLimit: 30,
    renalNote: "Adjust in significant CKD.",
  },
  {
    id: "metronidazole",
    name: "Metronidazole (Flagyl / Metrogyl)",
    class: "Nitroimidazole antibiotic / antiprotozoal",
    standardDose: "400–500 mg PO TID (indication-dependent)",
    pediatricDoseRule: "Metronidazole: often 7.5 mg/kg/dose TID",
    pediatricMgPerKgDay: 22.5,
    pediatricDoseUnit: "mg/kg/day",
    renalAdjustmentLimit: 10,
    renalNote: "Metabolites accumulate in severe renal failure — use caution.",
  },
  {
    id: "tinidazole",
    name: "Tinidazole (Tiniba)",
    class: "Nitroimidazole",
    standardDose: "2 g PO single dose or 500 mg BID × days (indication-dependent)",
  },
  {
    id: "doxycycline",
    name: "Doxycycline (Doxt / Microdox)",
    class: "Tetracycline antibiotic",
    standardDose: "100 mg PO BID (or 100 mg daily after load)",
  },
  {
    id: "tetracycline",
    name: "Tetracycline",
    class: "Tetracycline antibiotic",
    standardDose: "250–500 mg PO QID on empty stomach",
  },
  {
    id: "nitrofurantoin",
    name: "Nitrofurantoin (Martifur / Furadantin)",
    class: "Urinary antibiotic",
    standardDose: "100 mg PO BID (macrocrystals) × 5–7 days (uncomplicated UTI)",
    renalAdjustmentLimit: 30,
    renalNote: "Avoid when CrCl < ~30–60 mL/min (efficacy/toxicity concerns).",
    geriatricGuidelines: [
      {
        type: "Beers",
        ruleDescription: "Avoid for long-term suppression; avoid if CrCl low.",
        recommendation: "Short courses only when CrCl adequate",
      },
    ],
  },
  {
    id: "cotrimoxazole",
    name: "Co-trimoxazole / TMP-SMX (Septran / Bactrim)",
    class: "Sulfa antibiotic",
    standardDose: "1 DS tablet (160/800 mg) PO BID",
    pediatricDoseRule: "TMP component often 6–12 mg/kg/day ÷ BID",
    pediatricMgPerKgDay: 8,
    pediatricDoseUnit: "mg/kg/day",
    renalAdjustmentLimit: 30,
    renalNote: "Dose-adjust or avoid in significant CKD; hyperkalaemia risk.",
  },
  {
    id: "linezolid",
    name: "Linezolid (Linox / Zyvox)",
    class: "Oxazolidinone antibiotic",
    standardDose: "600 mg PO/IV BID",
  },
  {
    id: "vancomycin",
    name: "Vancomycin",
    class: "Glycopeptide antibiotic",
    standardDose: "15–20 mg/kg IV q8–12h (level-guided)",
    renalAdjustmentLimit: 50,
    renalNote: "Mandatory dose/interval adjustment by CrCl; trough monitoring.",
  },
  {
    id: "gentamicin",
    name: "Gentamicin",
    class: "Aminoglycoside antibiotic",
    standardDose: "3–7 mg/kg/day IV (extended-interval or divided; level-guided)",
    renalAdjustmentLimit: 60,
    renalNote: "High nephro/ototoxicity risk — adjust by CrCl and levels.",
  },
  {
    id: "amikacin",
    name: "Amikacin",
    class: "Aminoglycoside antibiotic",
    standardDose: "15 mg/kg/day IV (often once daily; level-guided)",
    renalAdjustmentLimit: 60,
    renalNote: "Adjust by renal function; monitor levels.",
  },
  {
    id: "piperacillin-tazobactam",
    name: "Piperacillin-Tazobactam (Piptaz / Zosyn)",
    class: "Antipseudomonal penicillin + BLI",
    standardDose: "4.5 g IV q6–8h (indication/CrCl dependent)",
    renalAdjustmentLimit: 40,
    renalNote: "Extend interval in CKD.",
  },
  {
    id: "meropenem",
    name: "Meropenem (Meronem)",
    class: "Carbapenem antibiotic",
    standardDose: "1 g IV q8h (higher for meningitis)",
    renalAdjustmentLimit: 50,
    renalNote: "Dose-adjust in renal impairment.",
  },
  {
    id: "imipenem-cilastatin",
    name: "Imipenem-Cilastatin",
    class: "Carbapenem antibiotic",
    standardDose: "500 mg–1 g IV q6–8h",
    renalAdjustmentLimit: 70,
    renalNote: "Adjust in CKD; seizure risk if not dose-adjusted.",
  },
  {
    id: "clindamycin",
    name: "Clindamycin (Dalacin / Clindac)",
    class: "Lincosamide antibiotic",
    standardDose: "150–450 mg PO QID or 600–900 mg IV q8h",
    pediatricDoseRule: "Clindamycin: often 10–40 mg/kg/day ÷ TID–QID",
    pediatricMgPerKgDay: 20,
    pediatricDoseUnit: "mg/kg/day",
  },
  {
    id: "fluconazole",
    name: "Fluconazole (Forcan / Diflucan)",
    class: "Azole antifungal",
    standardDose: "150 mg PO single (vaginal) or 200–400 mg daily (systemic)",
    renalAdjustmentLimit: 50,
    renalNote: "Reduce maintenance dose when CrCl < 50 for multi-dose courses.",
  },
  {
    id: "albendazole",
    name: "Albendazole (Zentel / Noworm)",
    class: "Anthelmintic",
    standardDose: "400 mg PO single or OD × 3 days (indication-dependent)",
  },
  {
    id: "ivermectin",
    name: "Ivermectin (Ivecop)",
    class: "Anthelmintic / antiparasitic",
    standardDose: "150–200 mcg/kg PO single (weight-based; indication-dependent)",
  },

  // —— GI ——
  {
    id: "omeprazole",
    name: "Omeprazole (Omez / Prilosec)",
    class: "PPI",
    standardDose: "20–40 mg PO daily",
    geriatricGuidelines: [
      {
        type: "Beers",
        ruleDescription:
          "Avoid scheduled PPI use >8 weeks without strong indication (C. diff, bone loss, B12 risk).",
        recommendation: "Deprescribe if no indication",
      },
    ],
  },
  {
    id: "pantoprazole",
    name: "Pantoprazole (Pan / Pantocid)",
    class: "PPI",
    standardDose: "40 mg PO daily",
  },
  {
    id: "rabeprazole",
    name: "Rabeprazole (Razo / Rabicip)",
    class: "PPI",
    standardDose: "20 mg PO daily",
  },
  {
    id: "esomeprazole",
    name: "Esomeprazole (Nexium / Sompraz)",
    class: "PPI",
    standardDose: "20–40 mg PO daily",
  },
  {
    id: "ranitidine",
    name: "Ranitidine (legacy H2RA — limited availability)",
    class: "H2 receptor antagonist",
    standardDose: "150 mg PO BID (where still available)",
    renalAdjustmentLimit: 50,
    renalNote: "Dose-adjust in CKD.",
  },
  {
    id: "famotidine",
    name: "Famotidine (Famocid)",
    class: "H2 receptor antagonist",
    standardDose: "20–40 mg PO daily–BID",
    renalAdjustmentLimit: 50,
    renalNote: "Reduce dose in significant CKD.",
  },
  {
    id: "domperidone",
    name: "Domperidone (Domstal / Motilium)",
    class: "Prokinetic / antiemetic (D2 antagonist)",
    standardDose: "10 mg PO TID before meals (short course)",
  },
  {
    id: "ondansetron",
    name: "Ondansetron (Emeset / Zofran)",
    class: "5-HT3 antagonist antiemetic",
    standardDose: "4–8 mg PO/IV q8–12h PRN",
    pediatricDoseRule: "Ondansetron: often 0.15 mg/kg/dose (max per label)",
    pediatricMgPerKgDay: 0.45,
    pediatricDoseUnit: "mg/kg/day",
  },
  {
    id: "metoclopramide",
    name: "Metoclopramide (Perinorm / Reglan)",
    class: "Prokinetic / antiemetic",
    standardDose: "10 mg PO/IV TID",
    renalAdjustmentLimit: 40,
    renalNote: "Reduce dose in CKD; EPS / tardive risk.",
    geriatricGuidelines: [
      {
        type: "Beers",
        ruleDescription: "Metoclopramide — EPS and tardive dyskinesia risk.",
        recommendation: "Avoid unless short-term gastroparesis",
      },
    ],
  },
  {
    id: "loperamide",
    name: "Loperamide (Imodium / Lopamide)",
    class: "Antidiarrhoeal",
    standardDose: "4 mg then 2 mg after each loose stool (max per label)",
  },
  {
    id: "ors",
    name: "ORS (Oral Rehydration Solution)",
    class: "Fluid / electrolyte replacement",
    standardDose: "Sip after each loose stool; WHO ORS as per dehydration plan",
  },
  {
    id: "lactulose",
    name: "Lactulose (Duphalac / Loosz)",
    class: "Osmotic laxative",
    standardDose: "15–30 ml PO BID–TID (titrate to soft stools)",
  },
  {
    id: "sucralfate",
    name: "Sucralfate (Sucrafil)",
    class: "Mucosal protectant",
    standardDose: "1 g PO QID on empty stomach",
  },

  // —— CV / metabolic ——
  {
    id: "amlodipine",
    name: "Amlodipine (Amlong / Norvasc)",
    class: "Dihydropyridine CCB",
    standardDose: "2.5–10 mg PO daily",
  },
  {
    id: "atenolol",
    name: "Atenolol (Aten / Tenormin)",
    class: "Beta-blocker",
    standardDose: "25–100 mg PO daily",
    renalAdjustmentLimit: 35,
    renalNote: "Reduce dose / extend interval in CKD.",
  },
  {
    id: "metoprolol",
    name: "Metoprolol (Metolar / Lopressor)",
    class: "Beta-blocker",
    standardDose: "25–100 mg PO BID (tartrate) or XL daily (succinate)",
  },
  {
    id: "bisoprolol",
    name: "Bisoprolol (Concor)",
    class: "Beta-blocker",
    standardDose: "1.25–10 mg PO daily",
  },
  {
    id: "enalapril",
    name: "Enalapril (Envas / Vasotec)",
    class: "ACE inhibitor",
    standardDose: "2.5–20 mg PO BID",
    renalAdjustmentLimit: 30,
    renalNote: "Start low / titrate cautiously in CKD; monitor K+ and creatinine.",
  },
  {
    id: "ramipril",
    name: "Ramipril (Cardace / Altace)",
    class: "ACE inhibitor",
    standardDose: "1.25–10 mg PO daily",
    renalAdjustmentLimit: 30,
    renalNote: "Dose-adjust in significant CKD; monitor electrolytes.",
  },
  {
    id: "telmisartan",
    name: "Telmisartan (Telma / Micardis)",
    class: "ARB",
    standardDose: "20–80 mg PO daily",
    renalAdjustmentLimit: 30,
    renalNote: "Monitor K+/Cr; caution in bilateral RAS / pregnancy.",
  },
  {
    id: "losartan",
    name: "Losartan (Losar / Cozaar)",
    class: "ARB",
    standardDose: "25–100 mg PO daily",
    renalAdjustmentLimit: 30,
    renalNote: "Monitor K+/Cr.",
  },
  {
    id: "olmesartan",
    name: "Olmesartan (Olmezest / Benicar)",
    class: "ARB",
    standardDose: "10–40 mg PO daily",
  },
  {
    id: "hydrochlorothiazide",
    name: "Hydrochlorothiazide (HCTZ)",
    class: "Thiazide diuretic",
    standardDose: "12.5–25 mg PO daily",
    renalAdjustmentLimit: 30,
    renalNote: "Less effective when CrCl very low.",
  },
  {
    id: "furosemide",
    name: "Furosemide (Lasix)",
    class: "Loop diuretic",
    standardDose: "20–80 mg PO/IV (titrate)",
  },
  {
    id: "spironolactone",
    name: "Spironolactone (Aldactone)",
    class: "Mineralocorticoid receptor antagonist",
    standardDose: "12.5–50 mg PO daily",
    renalAdjustmentLimit: 30,
    renalNote: "Hyperkalaemia risk rises as GFR falls — hold/reduce in advanced CKD.",
  },
  {
    id: "atorvastatin",
    name: "Atorvastatin (Atorva / Lipitor)",
    class: "Statin",
    standardDose: "10–80 mg PO HS",
  },
  {
    id: "rosuvastatin",
    name: "Rosuvastatin (Rosuvas / Crestor)",
    class: "Statin",
    standardDose: "5–40 mg PO daily",
    renalAdjustmentLimit: 30,
    renalNote: "Start lower doses in significant CKD.",
  },
  {
    id: "clopidogrel",
    name: "Clopidogrel (Clopitab / Plavix)",
    class: "P2Y12 inhibitor (antiplatelet)",
    standardDose: "75 mg PO daily",
  },
  {
    id: "ticagrelor",
    name: "Ticagrelor (Brilinta)",
    class: "P2Y12 inhibitor (antiplatelet)",
    standardDose: "90 mg PO BID after loading (ACS protocols)",
  },
  {
    id: "warfarin",
    name: "Warfarin (Warf / Coumadin)",
    class: "Vitamin K antagonist",
    standardDose: "Individualized INR-guided dosing",
  },
  {
    id: "apixaban",
    name: "Apixaban (Eliquis)",
    class: "DOAC (factor Xa inhibitor)",
    standardDose: "5 mg PO BID (2.5 mg BID if dose-reduction criteria met)",
    renalAdjustmentLimit: 30,
    renalNote: "Dose-adjust / avoid per label in advanced CKD / dialysis context.",
  },
  {
    id: "rivaroxaban",
    name: "Rivaroxaban (Xarelto)",
    class: "DOAC (factor Xa inhibitor)",
    standardDose: "20 mg PO daily with food (AF); VTE regimens differ",
    renalAdjustmentLimit: 50,
    renalNote: "Dose-adjust by CrCl per indication.",
  },
  {
    id: "amiodarone",
    name: "Amiodarone (Cordarone)",
    class: "Class III antiarrhythmic",
    standardDose: "200 mg PO daily (maintenance)",
    geriatricGuidelines: [
      {
        type: "Beers",
        ruleDescription:
          "Amiodarone may be appropriate for arrhythmia but requires monitoring; avoid as first-line for AF rate control in some contexts.",
        recommendation: "Use with monitoring; prefer safer options when possible",
      },
    ],
  },
  {
    id: "digoxin",
    name: "Digoxin (Lanoxin)",
    class: "Cardiac glycoside",
    standardDose: "0.125–0.25 mg PO daily",
    renalAdjustmentLimit: 50,
    renalNote: "Reduce dose / increase monitoring when CrCl reduced; toxicity risk rises.",
    geriatricGuidelines: [
      {
        type: "Beers",
        ruleDescription:
          "Avoid as first-line for AF rate control; higher toxicity risk if doses >0.125 mg/day in older adults.",
        recommendation: "Reduce dose / reconsider indication",
      },
      {
        type: "STOPP",
        ruleDescription:
          "STOPP: Digoxin at doses >125 mcg/day with renal impairment in older adults.",
        recommendation: "Reduce dose",
      },
    ],
  },
  {
    id: "isosorbide-mononitrate",
    name: "Isosorbide Mononitrate (Monotrate / Imdur)",
    class: "Nitrate",
    standardDose: "30–60 mg PO daily (nitrate-free interval)",
  },
  {
    id: "glyceryl-trinitrate",
    name: "Glyceryl Trinitrate / GTN (Angised / Nitrostat)",
    class: "Nitrate",
    standardDose: "0.3–0.6 mg SL PRN angina",
  },

  // —— Diabetes / endocrine ——
  {
    id: "metformin",
    name: "Metformin (Glycomet / Glucophage)",
    class: "Biguanide",
    standardDose: "500–1000 mg PO BID",
    renalAdjustmentLimit: 45,
    renalNote: "Reassess / avoid when eGFR/CrCl too low (lactic acidosis risk).",
  },
  {
    id: "glimepiride",
    name: "Glimepiride (Amaryl / Glimestar)",
    class: "Sulfonylurea",
    standardDose: "1–4 mg PO daily",
    renalAdjustmentLimit: 30,
    renalNote: "Hypoglycaemia risk rises in CKD/elderly — use low dose or avoid.",
    geriatricGuidelines: [
      {
        type: "Beers",
        ruleDescription: "Sulfonylureas — prolonged hypoglycaemia risk in older adults.",
        recommendation: "Prefer safer agents when possible",
      },
    ],
  },
  {
    id: "gliclazide",
    name: "Gliclazide (Diamicron)",
    class: "Sulfonylurea",
    standardDose: "40–80 mg PO daily–BID (MR formulations differ)",
  },
  {
    id: "sitagliptin",
    name: "Sitagliptin (Januvia / Istavel)",
    class: "DPP-4 inhibitor",
    standardDose: "100 mg PO daily",
    renalAdjustmentLimit: 45,
    renalNote: "Reduce dose by eGFR per label.",
  },
  {
    id: "dapagliflozin",
    name: "Dapagliflozin (Forxiga / Oxra)",
    class: "SGLT2 inhibitor",
    standardDose: "10 mg PO daily",
    renalAdjustmentLimit: 45,
    renalNote: "Glycaemic efficacy falls as GFR falls; still used for cardiorenal indications per label.",
  },
  {
    id: "empagliflozin",
    name: "Empagliflozin (Jardiance)",
    class: "SGLT2 inhibitor",
    standardDose: "10–25 mg PO daily",
    renalAdjustmentLimit: 45,
    renalNote: "Follow label for initiation thresholds by eGFR.",
  },
  {
    id: "insulin-regular",
    name: "Insulin Regular / Actrapid",
    class: "Short-acting insulin",
    standardDose: "Individualized SC/IV units",
  },
  {
    id: "insulin-glargine",
    name: "Insulin Glargine (Lantus / Basalog)",
    class: "Long-acting basal insulin",
    standardDose: "Individualized SC units once daily",
  },
  {
    id: "thyroxine",
    name: "Levothyroxine (Thyronorm / Eltroxin)",
    class: "Thyroid hormone",
    standardDose: "25–150 mcg PO daily empty stomach (TSH-guided)",
  },
  {
    id: "prednisolone",
    name: "Prednisolone (Wysolone)",
    class: "Systemic corticosteroid",
    standardDose: "5–60 mg PO daily (indication-dependent; taper when needed)",
  },
  {
    id: "dexamethasone",
    name: "Dexamethasone (Decadron / Dexona)",
    class: "Systemic corticosteroid",
    standardDose: "0.5–8 mg PO/IV (indication-dependent)",
  },
  {
    id: "hydrocortisone",
    name: "Hydrocortisone",
    class: "Systemic corticosteroid",
    standardDose: "Stress/replacement dosing IV/PO per protocol",
  },

  // —— Respiratory ——
  {
    id: "salbutamol",
    name: "Salbutamol / Albuterol (Asthalin)",
    class: "Short-acting beta-agonist",
    standardDose: "100–200 mcg inhaled PRN; neb 2.5–5 mg",
    pediatricDoseRule: "Neb/MDI weight-based per protocol",
  },
  {
    id: "budesonide",
    name: "Budesonide (Budecort / Pulmicort)",
    class: "Inhaled corticosteroid",
    standardDose: "Inhaled mcg BID per asthma/COPD step",
  },
  {
    id: "montelukast",
    name: "Montelukast (Montair / Singulair)",
    class: "Leukotriene receptor antagonist",
    standardDose: "10 mg PO HS (adult); age-banded paediatric chew/tabs",
  },
  {
    id: "theophylline",
    name: "Theophylline (Theo-Asthalin / Unicontin)",
    class: "Methylxanthine",
    standardDose: "Individualized; narrow therapeutic index",
    geriatricGuidelines: [
      {
        type: "Beers",
        ruleDescription: "Theophylline — toxicity, interactions; rarely first-line.",
        recommendation: "Avoid if safer inhaler therapy available",
      },
    ],
  },
  {
    id: "cetirizine",
    name: "Cetirizine (Cetzine / Zyrtec)",
    class: "2nd-generation antihistamine",
    standardDose: "10 mg PO daily",
    renalAdjustmentLimit: 30,
    renalNote: "Reduce dose in significant CKD.",
  },
  {
    id: "levocetirizine",
    name: "Levocetirizine (Xyzal / Levocet)",
    class: "2nd-generation antihistamine",
    standardDose: "5 mg PO daily",
    renalAdjustmentLimit: 50,
    renalNote: "Dose-adjust in renal impairment.",
  },
  {
    id: "fexofenadine",
    name: "Fexofenadine (Allegra / Fexy)",
    class: "2nd-generation antihistamine",
    standardDose: "120–180 mg PO daily",
  },
  {
    id: "pheniramine",
    name: "Pheniramine (Avil)",
    class: "1st-generation antihistamine",
    standardDose: "25 mg PO BID–TID",
    geriatricGuidelines: [
      {
        type: "Beers",
        ruleDescription: "First-generation antihistamines — anticholinergic / fall risk.",
        recommendation: "Avoid in older adults",
      },
    ],
  },
  {
    id: "chlorpheniramine",
    name: "Chlorpheniramine (CPM)",
    class: "1st-generation antihistamine",
    standardDose: "4 mg PO q4–6h PRN",
    geriatricGuidelines: [
      {
        type: "Beers",
        ruleDescription: "Anticholinergic antihistamine — delirium/fall risk.",
        recommendation: "Avoid in older adults",
      },
    ],
  },

  // —— Neuro / psych ——
  {
    id: "amitriptyline",
    name: "Amitriptyline (Tryptomer)",
    class: "TCA / Antidepressant",
    standardDose: "10–75 mg PO HS",
    geriatricGuidelines: [
      {
        type: "Beers",
        ruleDescription:
          "Highly anticholinergic TCA; associated with sedation, orthostasis, delirium, and falls in older adults.",
        recommendation: "Avoid",
      },
      {
        type: "STOPP",
        ruleDescription:
          "STOPP: Tricyclic antidepressants with anticholinergic effects in patients ≥65 years (especially with falls or cognitive impairment).",
        recommendation: "Stop / switch to safer alternative",
      },
    ],
  },
  {
    id: "sertraline",
    name: "Sertraline (Zoloft / Serta)",
    class: "SSRI antidepressant",
    standardDose: "25–100 mg PO daily",
  },
  {
    id: "escitalopram",
    name: "Escitalopram (Nexito / Lexapro)",
    class: "SSRI antidepressant",
    standardDose: "5–20 mg PO daily",
  },
  {
    id: "zolpidem",
    name: "Zolpidem (Zolfresh / Ambien)",
    class: "Sedative-hypnotic (Z-drug)",
    standardDose: "5–10 mg PO HS",
    geriatricGuidelines: [
      {
        type: "Beers",
        ruleDescription:
          "Non-benzodiazepine receptor agonist; increased risk of falls, fractures, delirium, and next-day impairment.",
        recommendation: "Avoid",
      },
      {
        type: "STOPP",
        ruleDescription:
          "STOPP: Hypnotic Z-drugs in older adults due to fall and fracture risk.",
        recommendation: "Stop; use non-pharmacologic sleep measures first",
      },
    ],
  },
  {
    id: "clonazepam",
    name: "Clonazepam (Clonotril / Klonopin)",
    class: "Benzodiazepine",
    standardDose: "0.25–1 mg PO BID (indication-dependent)",
    geriatricGuidelines: [
      {
        type: "Beers",
        ruleDescription: "Benzodiazepines — fall, delirium, dependence risk.",
        recommendation: "Avoid if possible",
      },
    ],
  },
  {
    id: "alprazolam",
    name: "Alprazolam (Alprax / Xanax)",
    class: "Benzodiazepine",
    standardDose: "0.25–0.5 mg PO TID PRN (short-term)",
    geriatricGuidelines: [
      {
        type: "Beers",
        ruleDescription: "Benzodiazepines — fall and cognitive risk.",
        recommendation: "Avoid",
      },
    ],
  },
  {
    id: "gabapentin",
    name: "Gabapentin (Neurontin / Gabapin)",
    class: "Anticonvulsant / neuropathic pain",
    standardDose: "300–600 mg PO TID (titrate)",
    renalAdjustmentLimit: 60,
    renalNote: "Mandatory dose reduction by CrCl.",
  },
  {
    id: "pregabalin",
    name: "Pregabalin (Lyrica / Pregaba)",
    class: "Anticonvulsant / neuropathic pain",
    standardDose: "75–150 mg PO BID (titrate)",
    renalAdjustmentLimit: 60,
    renalNote: "Reduce dose by renal function.",
  },
  {
    id: "phenytoin",
    name: "Phenytoin (Eptoin / Dilantin)",
    class: "Antiepileptic",
    standardDose: "Individualized; often 300–400 mg/day (level-guided)",
  },
  {
    id: "levetiracetam",
    name: "Levetiracetam (Keppra / Levera)",
    class: "Antiepileptic",
    standardDose: "500–1500 mg PO BID",
    renalAdjustmentLimit: 80,
    renalNote: "Dose-adjust by CrCl.",
  },

  // —— Vitamins / minerals / supplements (commonly prescribed) ——
  {
    id: "multivitamin",
    name: "Multivitamin (A–Z / Becosules / Supradyn / Zincovit)",
    class: "Multivitamin supplement",
    standardDose: "1 tablet/capsule PO daily after food",
  },
  {
    id: "vitamin-b-complex",
    name: "Vitamin B-Complex (Becosules / Neurobion)",
    class: "B-vitamin supplement",
    standardDose: "1 cap PO daily (or IM Neurobion per product)",
  },
  {
    id: "vitamin-b12",
    name: "Vitamin B12 / Methylcobalamin (Methycobal / Nurokind)",
    class: "Vitamin B12 supplement",
    standardDose: "1500 mcg PO daily or IM per deficiency protocol",
  },
  {
    id: "folic-acid",
    name: "Folic Acid (Folvite)",
    class: "Vitamin B9 supplement",
    standardDose: "5 mg PO daily (deficiency / pregnancy protocols vary)",
  },
  {
    id: "vitamin-d3",
    name: "Vitamin D3 / Cholecalciferol (Uprise-D3 / Calcirol)",
    class: "Vitamin D supplement",
    standardDose: "60000 IU PO weekly × 6–8 weeks then maintenance, or daily IU per level",
  },
  {
    id: "vitamin-c",
    name: "Vitamin C / Ascorbic acid (Celin / Limcee)",
    class: "Vitamin C supplement",
    standardDose: "500–1000 mg PO daily",
  },
  {
    id: "vitamin-a",
    name: "Vitamin A (Arovit)",
    class: "Vitamin A supplement",
    standardDose: "Per deficiency / age protocol (avoid excess in pregnancy)",
  },
  {
    id: "calcium-carbonate",
    name: "Calcium Carbonate (Shelcal / Calcimax / Ostocalcium)",
    class: "Calcium supplement / antacid",
    standardDose: "500–1000 mg elemental Ca PO with meals",
  },
  {
    id: "calcium-citrate",
    name: "Calcium Citrate",
    class: "Calcium supplement",
    standardDose: "Elemental Ca per label; often better absorbed fasting",
  },
  {
    id: "calcium-vitamin-d",
    name: "Calcium + Vitamin D (Shelcal-D / Calcimax-D)",
    class: "Calcium + vitamin D supplement",
    standardDose: "1 tablet PO daily–BID with meals (product-specific)",
  },
  {
    id: "iron-sulfate",
    name: "Iron / Ferrous salts (Tonoferon / Orofer / Dexorange / Fefol)",
    class: "Iron / haematinic supplement",
    standardDose: "Adult: ferrous sulfate ≈200 mg (≈65 mg elemental) OD–TID; children: 3–6 mg/kg/day elemental Fe",
    pediatricDoseRule: "Elemental iron 3–6 mg/kg/day for deficiency (OD–BD)",
    pediatricMgPerKgDay: 3,
    pediatricDoseUnit: "mg/kg/day",
  },
  {
    id: "tonoferon",
    name: "Tonoferon (Iron syrup / drops)",
    class: "Iron / haematinic syrup",
    standardDose: "Age/weight per Tonoferon label; target elemental Fe for deficiency",
    pediatricDoseRule: "Tonoferon syrup/drops — use label elemental Fe; ~3–6 mg/kg/day if deficient",
    pediatricMgPerKgDay: 3,
    pediatricDoseUnit: "mg/kg/day",
  },
  {
    id: "orofer-xt",
    name: "Orofer XT / Ferrous Ascorbate (syrup / tab)",
    class: "Iron / haematinic",
    standardDose: "Syrup or 100 mg elemental Fe tab OD (product-specific)",
    pediatricDoseRule: "Elemental iron ~3–6 mg/kg/day from Orofer XT syrup label",
    pediatricMgPerKgDay: 3,
    pediatricDoseUnit: "mg/kg/day",
  },
  {
    id: "dexorange",
    name: "Dexorange (FAC haematinic syrup)",
    class: "Iron / haematinic syrup",
    standardDose: "Per Dexorange label (often BD–TDS)",
    pediatricDoseRule: "Age-banded Dexorange paediatric syrup; confirm elemental Fe",
    pediatricMgPerKgDay: 3,
    pediatricDoseUnit: "mg/kg/day",
  },
  {
    id: "iron-folic",
    name: "Iron + Folic Acid (IFA / Autrin / Fefol-Z)",
    class: "Haematinic supplement",
    standardDose: "1 tablet PO daily (pregnancy/anaemia protocols)",
  },
  {
    id: "zinc-sulfate",
    name: "Zinc Sulfate / Zinc (Zinconia / Zincovit component)",
    class: "Zinc supplement",
    standardDose: "20 mg elemental Zn PO daily × 10–14 days (diarrhoea protocol) or OD supplement",
    pediatricDoseRule: "Zinc: age-banded 10–20 mg elemental daily in diarrhoea",
  },
  {
    id: "magnesium",
    name: "Magnesium (Magcid / magnesium oxide/citrate)",
    class: "Magnesium supplement",
    standardDose: "Per product elemental Mg; watch diarrhoea",
    renalAdjustmentLimit: 30,
    renalNote: "Avoid high-dose Mg in advanced CKD (hypermagnesaemia).",
  },
  {
    id: "potassium-chloride",
    name: "Potassium Chloride (Potklor / KCl)",
    class: "Electrolyte supplement",
    standardDose: "Individualized mEq PO/IV by K+ level",
    renalAdjustmentLimit: 30,
    renalNote: "Extreme caution in CKD — hyperkalaemia risk.",
  },
  {
    id: "ors-zinc",
    name: "ORS + Zinc (diarrhoeal pack)",
    class: "Rehydration + zinc",
    standardDose: "ORS per plan + zinc 10–20 mg elemental × 10–14 days",
  },

  // —— Misc common ——
  {
    id: "allopurinol",
    name: "Allopurinol (Zyloric)",
    class: "Xanthine oxidase inhibitor",
    standardDose: "100–300 mg PO daily (titrate; HLA-B*5801 caution)",
    renalAdjustmentLimit: 30,
    renalNote: "Start low and adjust in CKD.",
  },
  {
    id: "colchicine",
    name: "Colchicine",
    class: "Anti-gout",
    standardDose: "Acute flare regimens per guideline (low-dose preferred)",
    renalAdjustmentLimit: 30,
    renalNote: "Reduce dose / avoid in advanced CKD.",
  },
  {
    id: "tranexamic-acid",
    name: "Tranexamic Acid (Pause / Cyclokapron)",
    class: "Antifibrinolytic",
    standardDose: "500–1000 mg PO/IV TID (indication-dependent)",
    renalAdjustmentLimit: 50,
    renalNote: "Dose-adjust in renal impairment.",
  },
  {
    id: "adrenaline",
    name: "Adrenaline / Epinephrine",
    class: "Vasopressor / anaphylaxis",
    standardDose: "0.3–0.5 mg IM (anaphylaxis adult); IV infusion per protocol",
  },
  {
    id: "normal-saline",
    name: "Normal Saline 0.9%",
    class: "Isotonic crystalloid",
    standardDose: "IV volume as clinically indicated",
  },
  {
    id: "ringer-lactate",
    name: "Ringer Lactate / Hartmann",
    class: "Balanced crystalloid",
    standardDose: "IV volume as clinically indicated",
  },
];

export const interactionsDB: PracticalInteraction[] = [
  {
    drugAId: "ciprofloxacin",
    drugBId: "calcium-carbonate",
    severity: "Moderate",
    clinicalEffect:
      "Calcium chelates ciprofloxacin in the gut, markedly reducing fluoroquinolone absorption and clinical efficacy.",
    managementAction:
      "Separate administration; prefer taking ciprofloxacin 2 hours before or 4–6 hours after calcium products.",
    timingAdjustment: "Administer Ciprofloxacin 2–4 hours apart from Calcium Carbonate",
    isPracticallyDocumented: true,
  },
  {
    drugAId: "ciprofloxacin",
    drugBId: "calcium-vitamin-d",
    severity: "Moderate",
    clinicalEffect:
      "Calcium in combination products binds ciprofloxacin and reduces absorption.",
    managementAction: "Separate ciprofloxacin from calcium+D by 2–4 hours.",
    timingAdjustment: "Space Ciprofloxacin and Calcium+D by 2–4 hours",
    isPracticallyDocumented: true,
  },
  {
    drugAId: "ciprofloxacin",
    drugBId: "iron-sulfate",
    severity: "Moderate",
    clinicalEffect: "Iron salts chelate fluoroquinolones → reduced antibiotic levels.",
    managementAction: "Give ciprofloxacin ≥2 h before or 4–6 h after iron.",
    timingAdjustment: "Separate Ciprofloxacin and Iron by 2–6 hours",
    isPracticallyDocumented: true,
  },
  {
    drugAId: "ciprofloxacin",
    drugBId: "multivitamin",
    severity: "Moderate",
    clinicalEffect:
      "Multivitamins with minerals (Ca/Fe/Zn/Mg) can reduce fluoroquinolone absorption.",
    managementAction: "Separate ciprofloxacin from multivitamin-mineral products by several hours.",
    isPracticallyDocumented: true,
  },
  {
    drugAId: "levofloxacin",
    drugBId: "calcium-carbonate",
    severity: "Moderate",
    clinicalEffect: "Divalent cations reduce levofloxacin absorption.",
    managementAction: "Separate levofloxacin and calcium by 2–4 hours.",
    isPracticallyDocumented: true,
  },
  {
    drugAId: "ofloxacin",
    drugBId: "calcium-carbonate",
    severity: "Moderate",
    clinicalEffect: "Calcium reduces ofloxacin absorption.",
    managementAction: "Space doses by 2–4 hours.",
    isPracticallyDocumented: true,
  },
  {
    drugAId: "doxycycline",
    drugBId: "calcium-carbonate",
    severity: "Moderate",
    clinicalEffect: "Calcium chelates tetracyclines → reduced antibiotic effect.",
    managementAction: "Separate doxycycline and calcium by ≥2–3 hours.",
    timingAdjustment: "Space Doxycycline and Calcium",
    isPracticallyDocumented: true,
  },
  {
    drugAId: "doxycycline",
    drugBId: "iron-sulfate",
    severity: "Moderate",
    clinicalEffect: "Iron binds doxycycline and reduces absorption.",
    managementAction: "Separate iron and doxycycline by several hours.",
    isPracticallyDocumented: true,
  },
  {
    drugAId: "doxycycline",
    drugBId: "calcium-vitamin-d",
    severity: "Moderate",
    clinicalEffect: "Calcium in combo products reduces doxycycline absorption.",
    managementAction: "Separate administration by ≥2–3 hours.",
    isPracticallyDocumented: true,
  },
  {
    drugAId: "tetracycline",
    drugBId: "calcium-carbonate",
    severity: "Moderate",
    clinicalEffect: "Calcium–tetracycline chelation reduces antibiotic levels.",
    managementAction: "Avoid co-administration; separate by several hours.",
    isPracticallyDocumented: true,
  },
  {
    drugAId: "thyroxine",
    drugBId: "calcium-carbonate",
    severity: "Moderate",
    clinicalEffect: "Calcium reduces levothyroxine absorption.",
    managementAction: "Take thyroxine on empty stomach; separate calcium by ≥4 hours.",
    timingAdjustment: "Thyroxine morning empty stomach; Calcium later",
    isPracticallyDocumented: true,
  },
  {
    drugAId: "thyroxine",
    drugBId: "iron-sulfate",
    severity: "Moderate",
    clinicalEffect: "Iron reduces levothyroxine absorption.",
    managementAction: "Separate thyroxine and iron by ≥4 hours.",
    isPracticallyDocumented: true,
  },
  {
    drugAId: "thyroxine",
    drugBId: "calcium-vitamin-d",
    severity: "Moderate",
    clinicalEffect: "Calcium+D products reduce thyroxine absorption.",
    managementAction: "Separate by ≥4 hours.",
    isPracticallyDocumented: true,
  },
  {
    drugAId: "amiodarone",
    drugBId: "digoxin",
    severity: "Major",
    clinicalEffect:
      "Amiodarone inhibits P-gp and reduces digoxin clearance, raising digoxin levels and toxicity risk (bradycardia, GI, visual, arrhythmias).",
    managementAction:
      "Decrease Digoxin dose by approximately 50% when starting Amiodarone; monitor digoxin level and HR closely.",
    isPracticallyDocumented: true,
  },
  {
    drugAId: "clopidogrel",
    drugBId: "omeprazole",
    severity: "Major",
    clinicalEffect:
      "Omeprazole inhibits CYP2C19, reducing activation of clopidogrel and attenuating antiplatelet effect (higher CV event risk in practice).",
    managementAction:
      "Switch Omeprazole to Pantoprazole (or another weaker CYP2C19 inhibitor PPI) if gastroprotection is required.",
    isPracticallyDocumented: true,
  },
  {
    drugAId: "warfarin",
    drugBId: "metronidazole",
    severity: "Major",
    clinicalEffect: "Metronidazole potentiates warfarin → INR rise and bleeding risk.",
    managementAction: "Monitor INR closely; adjust warfarin; consider alternative antibiotic if feasible.",
    isPracticallyDocumented: true,
  },
  {
    drugAId: "warfarin",
    drugBId: "ciprofloxacin",
    severity: "Major",
    clinicalEffect: "Fluoroquinolones can raise INR with warfarin.",
    managementAction: "Increase INR monitoring; adjust warfarin as needed.",
    isPracticallyDocumented: true,
  },
  {
    drugAId: "spironolactone",
    drugBId: "enalapril",
    severity: "Major",
    clinicalEffect: "ACEI + MRA increase hyperkalaemia risk, especially in CKD.",
    managementAction: "Monitor K+ and creatinine; use low MRA doses; hold if K+ high.",
    isPracticallyDocumented: true,
  },
  {
    drugAId: "spironolactone",
    drugBId: "ramipril",
    severity: "Major",
    clinicalEffect: "ACEI + spironolactone → hyperkalaemia risk.",
    managementAction: "Monitor electrolytes closely.",
    isPracticallyDocumented: true,
  },
  {
    drugAId: "spironolactone",
    drugBId: "telmisartan",
    severity: "Major",
    clinicalEffect: "ARB + MRA → hyperkalaemia risk.",
    managementAction: "Monitor K+/Cr; caution in CKD.",
    isPracticallyDocumented: true,
  },
  {
    drugAId: "ibuprofen",
    drugBId: "enalapril",
    severity: "Moderate",
    clinicalEffect: "NSAID + ACEI can cause AKI (especially with diuretic — “triple whammy”).",
    managementAction: "Avoid chronic NSAID; monitor Cr; use paracetamol for pain when possible.",
    isPracticallyDocumented: true,
  },
  {
    drugAId: "ibuprofen",
    drugBId: "furosemide",
    severity: "Moderate",
    clinicalEffect: "NSAID blunts loop-diuretic effect and raises AKI risk.",
    managementAction: "Avoid combination when possible; monitor renal function.",
    isPracticallyDocumented: true,
  },
  {
    drugAId: "iron-sulfate",
    drugBId: "calcium-carbonate",
    severity: "Moderate",
    clinicalEffect: "Calcium can reduce iron absorption when taken together.",
    managementAction: "Separate iron and calcium by ≥2 hours.",
    timingAdjustment: "Space Iron and Calcium",
    isPracticallyDocumented: true,
  },
  {
    drugAId: "iron-folic",
    drugBId: "calcium-carbonate",
    severity: "Moderate",
    clinicalEffect: "Calcium reduces iron absorption from haematinics.",
    managementAction: "Separate doses by ≥2 hours.",
    isPracticallyDocumented: true,
  },
  {
    drugAId: "azithromycin",
    drugBId: "amiodarone",
    severity: "Major",
    clinicalEffect: "Additive QT prolongation risk.",
    managementAction: "Avoid combination if possible; monitor ECG/electrolytes if unavoidable.",
    isPracticallyDocumented: true,
  },
  {
    drugAId: "ondansetron",
    drugBId: "amiodarone",
    severity: "Moderate",
    clinicalEffect: "Additive QT prolongation potential.",
    managementAction: "Use caution; correct electrolytes; monitor if high risk.",
    isPracticallyDocumented: true,
  },
];

/** Extra search aliases → drug id (Indian brand / shorthand). */
const SEARCH_ALIASES: Record<string, string> = {
  amoxyclav: "amoxicillin-clavulanate",
  augmentin: "amoxicillin-clavulanate",
  clavam: "amoxicillin-clavulanate",
  moxclav: "amoxicillin-clavulanate",
  "amox clav": "amoxicillin-clavulanate",
  "amox-clav": "amoxicillin-clavulanate",
  monocef: "ceftriaxone",
  taxim: "cefixime",
  zifi: "cefixime",
  azithral: "azithromycin",
  azee: "azithromycin",
  ciplox: "ciprofloxacin",
  flagyl: "metronidazole",
  metrogyl: "metronidazole",
  septran: "cotrimoxazole",
  bactrim: "cotrimoxazole",
  shelcal: "calcium-carbonate",
  "shelcal d": "calcium-vitamin-d",
  "shelcal-d": "calcium-vitamin-d",
  calcimax: "calcium-carbonate",
  becosules: "vitamin-b-complex",
  neurobion: "vitamin-b-complex",
  zincovit: "multivitamin",
  supradyn: "multivitamin",
  orofer: "orofer-xt",
  "orofer xt": "orofer-xt",
  fefol: "iron-folic",
  dexorange: "dexorange",
  tonoferon: "tonoferon",
  tonoferron: "tonoferon",
  "tonoferon syrup": "tonoferon",
  "iron syrup": "iron-sulfate",
  folvite: "folic-acid",
  methycobal: "vitamin-b12",
  nurokind: "vitamin-b12",
  uprise: "vitamin-d3",
  calcirol: "vitamin-d3",
  dolo: "paracetamol",
  crocin: "paracetamol",
  pan: "pantoprazole",
  pantocid: "pantoprazole",
  omez: "omeprazole",
  lasix: "furosemide",
  telma: "telmisartan",
  amlong: "amlodipine",
  ecosprin: "aspirin",
  thyronorm: "thyroxine",
  eltroxin: "thyroxine",
  wysolone: "prednisolone",
  emeset: "ondansetron",
  asthalin: "salbutamol",
  montair: "montelukast",
  glycomet: "metformin",
  atorva: "atorvastatin",
  clopitab: "clopidogrel",
  piptaz: "piperacillin-tazobactam",
  meronem: "meropenem",
  doxt: "doxycycline",
  martifur: "nitrofurantoin",
  zinconia: "zinc-sulfate",
};

export function searchDrugs(query: string): DrugRecord[] {
  const q = query.trim().toLowerCase();
  if (!q) return drugsDB.slice(0, 24);

  const aliasId = SEARCH_ALIASES[q];
  const aliasHit = aliasId ? drugsDB.find((d) => d.id === aliasId) : undefined;

  const matched = drugsDB.filter(
    (d) =>
      d.name.toLowerCase().includes(q) ||
      d.class.toLowerCase().includes(q) ||
      d.id.includes(q) ||
      d.id.replace(/-/g, " ").includes(q) ||
      d.id.replace(/-/g, "").includes(q.replace(/[\s-]/g, "")),
  );

  if (aliasHit && !matched.some((d) => d.id === aliasHit.id)) {
    return [aliasHit, ...matched];
  }
  // Prefer alias hit first when query is a known brand
  if (aliasHit) {
    return [aliasHit, ...matched.filter((d) => d.id !== aliasHit.id)];
  }
  return matched;
}

export function getDrugById(id: string): DrugRecord | undefined {
  return drugsDB.find((d) => d.id === id);
}
