import type { DrugRecord } from "./types";

/**
 * Extended drug set — oncology (complete anticancer classes), remaining
 * anti-infectives, and the common drugs of every major specialty, taking
 * drugsDB past 500 entries. Doses are adult standard doses from usual
 * references (BNF, Lexicomp-style summaries, WHO/NCCN protocol norms);
 * chemotherapy doses are protocol-dependent — entries carry the usual
 * protocol dose for identification and interaction checking, not a
 * prescription.
 */
export const EXTENDED_DRUGS: DrugRecord[] = [
  // ============ ONCOLOGY — alkylating agents ============
  { id: "ifosfamide", name: "Ifosfamide (Holoxan)", class: "Chemo — alkylating agent",
    standardDose: "1.2–2.4 g/m²/day IV ×3–5 days per cycle, always with mesna",
    renalAdjustmentLimit: 60, renalNote: "Nephrotoxic (Fanconi risk); reduce dose CrCl < 60, avoid < 30." },
  { id: "chlorambucil", name: "Chlorambucil (Leukeran)", class: "Chemo — alkylating agent",
    standardDose: "0.1 mg/kg/day PO (CLL protocols)" },
  { id: "melphalan", name: "Melphalan (Alkeran)", class: "Chemo — alkylating agent",
    standardDose: "Myeloma: 0.15–0.25 mg/kg/day PO ×4 days per cycle; high-dose IV for transplant",
    renalAdjustmentLimit: 60, renalNote: "Reduce IV dose ~25–50% in renal impairment." },
  { id: "bendamustine", name: "Bendamustine (Innomustine)", class: "Chemo — alkylating agent",
    standardDose: "90–120 mg/m² IV days 1–2 per 28-day cycle",
    renalAdjustmentLimit: 40, renalNote: "Avoid if CrCl < 40." },
  { id: "busulfan", name: "Busulfan (Myleran)", class: "Chemo — alkylating agent",
    standardDose: "CML: 0.06 mg/kg/day PO; conditioning: IV per protocol with levels" },
  { id: "dacarbazine", name: "Dacarbazine (DTIC)", class: "Chemo — alkylating agent",
    standardDose: "375 mg/m² IV (ABVD day 1 & 15); melanoma 850–1000 mg/m² q3wk" },
  { id: "temozolomide", name: "Temozolomide (Temoside)", class: "Chemo — alkylating agent (oral)",
    standardDose: "Glioma: 75 mg/m²/day with RT, then 150–200 mg/m² days 1–5 q28d" },
  { id: "lomustine", name: "Lomustine (CCNU)", class: "Chemo — nitrosourea",
    standardDose: "100–130 mg/m² PO single dose q6 weeks (delayed marrow nadir)" },
  { id: "procarbazine", name: "Procarbazine (P-carzine)", class: "Chemo — alkylating agent",
    standardDose: "100 mg/m²/day PO days 1–14 (weak MAOI — tyramine and drug interactions)" },
  { id: "thiotepa", name: "Thiotepa", class: "Chemo — alkylating agent",
    standardDose: "Per protocol IV/intravesical/intrathecal" },

  // ============ ONCOLOGY — antimetabolites ============
  { id: "cytarabine", name: "Cytarabine (Cytosar / Ara-C)", class: "Chemo — antimetabolite",
    standardDose: "AML induction 100–200 mg/m²/day CIVI ×7d; HiDAC 1–3 g/m² q12h (cerebellar toxicity watch)",
    renalAdjustmentLimit: 60, renalNote: "Reduce high-dose regimens in renal impairment (neurotoxicity)." },
  { id: "azacitidine", name: "Azacitidine (Azadine)", class: "Chemo — hypomethylating agent",
    standardDose: "75 mg/m² SC/IV days 1–7 q28d (MDS/AML)" },
  { id: "decitabine", name: "Decitabine (Dacogen)", class: "Chemo — hypomethylating agent",
    standardDose: "20 mg/m² IV days 1–5 q28d" },
  { id: "fludarabine", name: "Fludarabine (Fludara)", class: "Chemo — purine analogue",
    standardDose: "25 mg/m² IV days 1–5 q28d (CLL; profound lymphopenia — irradiated blood only)",
    renalAdjustmentLimit: 70, renalNote: "Reduce 20–50% CrCl 30–70; avoid < 30." },
  { id: "cladribine", name: "Cladribine", class: "Chemo — purine analogue",
    standardDose: "0.09 mg/kg/day CIVI ×7d (hairy cell leukemia)" },
  { id: "mercaptopurine", name: "Mercaptopurine (Purinethol / 6-MP)", class: "Chemo — purine analogue",
    standardDose: "ALL maintenance: 50–75 mg/m²/day PO at night; QUARTER the dose with allopurinol/febuxostat" },
  { id: "thioguanine", name: "Thioguanine (6-TG)", class: "Chemo — purine analogue",
    standardDose: "AML protocols: 60–200 mg/m²/day PO" },
  { id: "pemetrexed", name: "Pemetrexed (Pemgem)", class: "Chemo — antifolate",
    standardDose: "500 mg/m² IV q21d with B12 + folic acid supplementation (non-squamous NSCLC, mesothelioma)",
    renalAdjustmentLimit: 45, renalNote: "Do not give if CrCl < 45." },
  { id: "hydroxyurea", name: "Hydroxyurea (Hydrea / Cytodrox)", class: "Chemo — antimetabolite",
    standardDose: "CML/ET/PV cytoreduction: 15–30 mg/kg/day PO; sickle cell: 15–35 mg/kg/day",
    renalAdjustmentLimit: 60, renalNote: "Halve dose CrCl < 60." },

  // ============ ONCOLOGY — anthracyclines & antitumor antibiotics ============
  { id: "daunorubicin", name: "Daunorubicin", class: "Chemo — anthracycline",
    standardDose: "AML 3+7: 60–90 mg/m²/day IV days 1–3 (lifetime cumulative cardiotoxicity limit)" },
  { id: "epirubicin", name: "Epirubicin (Epirubi)", class: "Chemo — anthracycline",
    standardDose: "75–100 mg/m² IV q21d (breast); cumulative limit ~900 mg/m²" },
  { id: "idarubicin", name: "Idarubicin (Zavedos)", class: "Chemo — anthracycline",
    standardDose: "12 mg/m²/day IV days 1–3 (AML induction)" },
  { id: "mitoxantrone", name: "Mitoxantrone", class: "Chemo — anthracenedione",
    standardDose: "12 mg/m² IV days 1–3 (AML); cardiotoxic — echo before and during" },
  { id: "bleomycin", name: "Bleomycin (Bleocip)", class: "Chemo — antitumor antibiotic",
    standardDose: "10 units/m² IV/IM (ABVD days 1 & 15); lifetime max ~400 units — pulmonary fibrosis risk, baseline PFT/DLCO",
    renalAdjustmentLimit: 50, renalNote: "Reduce 25–50% CrCl < 50 (renally cleared, lung toxicity rises)." },
  { id: "mitomycin", name: "Mitomycin C (Mitocin)", class: "Chemo — antitumor antibiotic",
    standardDose: "Intravesical 40 mg (bladder); IV 10 mg/m² per protocol (HUS risk with cumulative dosing)" },
  { id: "dactinomycin", name: "Dactinomycin (Actinomycin D)", class: "Chemo — antitumor antibiotic",
    standardDose: "Wilms/rhabdo protocols: 15 µg/kg/day IV ×5d (severe vesicant)" },

  // ============ ONCOLOGY — topoisomerase inhibitors ============
  { id: "etoposide", name: "Etoposide (Etosid)", class: "Chemo — topoisomerase II inhibitor",
    standardDose: "100 mg/m²/day IV days 1–3 (BEP); 50 mg/m²/day PO ×21d per protocol",
    renalAdjustmentLimit: 50, renalNote: "Reduce 25% CrCl 15–50." },
  { id: "irinotecan", name: "Irinotecan (Irnocam)", class: "Chemo — topoisomerase I inhibitor",
    standardDose: "180 mg/m² IV q2wk (FOLFIRI); severe delayed diarrhoea — loperamide protocol; UGT1A1 poor metabolisers need lower dose" },
  { id: "topotecan", name: "Topotecan (Topotec)", class: "Chemo — topoisomerase I inhibitor",
    standardDose: "1.5 mg/m²/day IV days 1–5 q21d (ovary, SCLC)",
    renalAdjustmentLimit: 40, renalNote: "0.75 mg/m² if CrCl 20–39." },

  // ============ ONCOLOGY — microtubule agents ============
  { id: "vinblastine", name: "Vinblastine", class: "Chemo — vinca alkaloid",
    standardDose: "6 mg/m² IV (ABVD days 1 & 15); NEVER intrathecal — fatal" },
  { id: "vinorelbine", name: "Vinorelbine (Vinelbine)", class: "Chemo — vinca alkaloid",
    standardDose: "25–30 mg/m² IV weekly, or 60–80 mg/m² PO weekly" },
  { id: "cabazitaxel", name: "Cabazitaxel (Cabazine)", class: "Chemo — taxane",
    standardDose: "20–25 mg/m² IV q21d with prednisolone (post-docetaxel prostate cancer)" },
  { id: "eribulin", name: "Eribulin (Halaven)", class: "Chemo — microtubule inhibitor",
    standardDose: "1.4 mg/m² IV days 1 & 8 q21d (late-line breast cancer)",
    renalAdjustmentLimit: 50, renalNote: "1.1 mg/m² if CrCl 15–49." },

  // ============ ONCOLOGY — TKIs & targeted oral agents ============
  { id: "dasatinib", name: "Dasatinib (Dasanat)", class: "Targeted — BCR-ABL TKI",
    standardDose: "100 mg PO OD (CML chronic phase); pleural effusion watch; avoid PPIs (absorption)" },
  { id: "nilotinib", name: "Nilotinib (Tasigna)", class: "Targeted — BCR-ABL TKI",
    standardDose: "300 mg PO BID on empty stomach (QT prolongation — ECG monitoring)" },
  { id: "bosutinib", name: "Bosutinib", class: "Targeted — BCR-ABL TKI",
    standardDose: "400–500 mg PO OD with food (diarrhoea common)" },
  { id: "erlotinib", name: "Erlotinib (Erlocip)", class: "Targeted — EGFR TKI",
    standardDose: "150 mg PO OD empty stomach (EGFR-mutant NSCLC); rash/diarrhoea; PPIs reduce absorption" },
  { id: "gefitinib", name: "Gefitinib (Geftinat)", class: "Targeted — EGFR TKI",
    standardDose: "250 mg PO OD (EGFR-mutant NSCLC); ILD watch" },
  { id: "osimertinib", name: "Osimertinib (Tagrisso / Osicent)", class: "Targeted — EGFR TKI (3rd gen)",
    standardDose: "80 mg PO OD (first-line EGFR-mutant NSCLC and T790M); QT and cardiomyopathy monitoring" },
  { id: "afatinib", name: "Afatinib (Xovoltib)", class: "Targeted — EGFR TKI",
    standardDose: "40 mg PO OD empty stomach" },
  { id: "crizotinib", name: "Crizotinib (Crizalk)", class: "Targeted — ALK/ROS1 TKI",
    standardDose: "250 mg PO BID (ALK/ROS1-positive NSCLC); bradycardia, visual effects" },
  { id: "alectinib", name: "Alectinib (Alecensa)", class: "Targeted — ALK TKI",
    standardDose: "600 mg PO BID with food (first-line ALK-positive NSCLC; CNS-active)" },
  { id: "lorlatinib", name: "Lorlatinib", class: "Targeted — ALK TKI (3rd gen)",
    standardDose: "100 mg PO OD (lipids and cognitive effects monitoring)" },
  { id: "sunitinib", name: "Sunitinib (Sutent)", class: "Targeted — multikinase inhibitor",
    standardDose: "RCC/GIST: 50 mg PO OD 4-weeks-on/2-off (hypertension, hypothyroidism, hand-foot)" },
  { id: "sorafenib", name: "Sorafenib (Soranib)", class: "Targeted — multikinase inhibitor",
    standardDose: "400 mg PO BID empty stomach (HCC, RCC, DTC)" },
  { id: "lenvatinib", name: "Lenvatinib (Lenvima)", class: "Targeted — multikinase inhibitor",
    standardDose: "Thyroid 24 mg OD; HCC 8–12 mg OD by weight (severe hypertension watch)" },
  { id: "regorafenib", name: "Regorafenib (Resihance)", class: "Targeted — multikinase inhibitor",
    standardDose: "160 mg PO OD days 1–21 q28d (refractory CRC, GIST)" },
  { id: "pazopanib", name: "Pazopanib (Votrient)", class: "Targeted — multikinase inhibitor",
    standardDose: "800 mg PO OD empty stomach (RCC, soft-tissue sarcoma); hepatotoxicity — LFT monitoring" },
  { id: "axitinib", name: "Axitinib (Inlyta)", class: "Targeted — VEGFR TKI",
    standardDose: "5 mg PO BID, titrate (RCC)" },
  { id: "cabozantinib", name: "Cabozantinib (Cabometyx)", class: "Targeted — multikinase inhibitor",
    standardDose: "60 mg PO OD empty stomach (RCC, HCC)" },
  { id: "ibrutinib", name: "Ibrutinib (Imbruvica)", class: "Targeted — BTK inhibitor",
    standardDose: "CLL 420 mg PO OD (AF and bleeding risk — caution with anticoagulants)" },
  { id: "acalabrutinib", name: "Acalabrutinib (Calquence)", class: "Targeted — BTK inhibitor",
    standardDose: "100 mg PO BID (less AF than ibrutinib; avoid PPIs with capsule form)" },
  { id: "ruxolitinib", name: "Ruxolitinib (Jakavi)", class: "Targeted — JAK1/2 inhibitor",
    standardDose: "Myelofibrosis: 5–20 mg PO BID by platelet count; do not stop abruptly",
    renalAdjustmentLimit: 60, renalNote: "Reduce starting dose in renal impairment." },
  { id: "palbociclib", name: "Palbociclib (Ibrance / Palbace)", class: "Targeted — CDK4/6 inhibitor",
    standardDose: "125 mg PO OD days 1–21 q28d with endocrine therapy (neutropenia — CBC monitoring)" },
  { id: "ribociclib", name: "Ribociclib (Kryxana)", class: "Targeted — CDK4/6 inhibitor",
    standardDose: "600 mg PO OD days 1–21 q28d (QT prolongation — ECG at baseline and on treatment)" },
  { id: "abemaciclib", name: "Abemaciclib (Verzenio)", class: "Targeted — CDK4/6 inhibitor",
    standardDose: "150 mg PO BID continuous (diarrhoea common; VTE risk)" },
  { id: "everolimus", name: "Everolimus (Advacan)", class: "Targeted — mTOR inhibitor",
    standardDose: "Oncology 10 mg PO OD; transplant 0.75–1 mg BID with levels (stomatitis, pneumonitis, hyperglycemia)" },
  { id: "lapatinib", name: "Lapatinib (Herduo)", class: "Targeted — HER2 TKI",
    standardDose: "1250 mg PO OD empty stomach with capecitabine" },
  { id: "olaparib", name: "Olaparib (Lynparza)", class: "Targeted — PARP inhibitor",
    standardDose: "300 mg PO BID (BRCA-mutant ovary/breast/pancreas/prostate)",
    renalAdjustmentLimit: 50, renalNote: "200 mg BID if CrCl 31–50." },
  { id: "venetoclax", name: "Venetoclax (Venclexta)", class: "Targeted — BCL-2 inhibitor",
    standardDose: "CLL: 5-week ramp-up 20→400 mg OD (tumour lysis prophylaxis mandatory)" },
  { id: "vemurafenib", name: "Vemurafenib (Zelboraf)", class: "Targeted — BRAF inhibitor",
    standardDose: "960 mg PO BID (BRAF V600E melanoma); photosensitivity, new SCCs" },
  { id: "dabrafenib", name: "Dabrafenib (Rafinlar)", class: "Targeted — BRAF inhibitor",
    standardDose: "150 mg PO BID empty stomach, usually with trametinib (pyrexia syndrome)" },
  { id: "trametinib", name: "Trametinib (Mekinist)", class: "Targeted — MEK inhibitor",
    standardDose: "2 mg PO OD with dabrafenib (cardiomyopathy — echo monitoring)" },

  // ============ ONCOLOGY — monoclonals & immunotherapy ============
  { id: "rituximab", name: "Rituximab (Ristova / MabTas)", class: "Monoclonal — anti-CD20",
    standardDose: "375 mg/m² IV per cycle (NHL/CLL) — screen HBsAg AND anti-HBc first (HBV reactivation)" },
  { id: "obinutuzumab", name: "Obinutuzumab (Gazyva)", class: "Monoclonal — anti-CD20",
    standardDose: "1000 mg IV days 1, 8, 15 of cycle 1 then per cycle (infusion reactions — premedicate)" },
  { id: "trastuzumab", name: "Trastuzumab (Herclon / CANMAb)", class: "Monoclonal — anti-HER2",
    standardDose: "8 mg/kg IV load then 6 mg/kg q3wk (HER2+ breast/gastric); echo every 3 months — cardiotoxic, additive with anthracyclines" },
  { id: "pertuzumab", name: "Pertuzumab (Perjeta)", class: "Monoclonal — anti-HER2",
    standardDose: "840 mg IV load then 420 mg q3wk with trastuzumab" },
  { id: "bevacizumab", name: "Bevacizumab (Avastin / Bevatas)", class: "Monoclonal — anti-VEGF",
    standardDose: "5–15 mg/kg IV q2–3wk (hypertension, proteinuria, bleeding/perforation; stop 4–6 wk before surgery)" },
  { id: "cetuximab", name: "Cetuximab (Erbitux)", class: "Monoclonal — anti-EGFR",
    standardDose: "400 mg/m² IV load then 250 mg/m² weekly (RAS wild-type CRC, head & neck); acneiform rash, hypomagnesemia" },
  { id: "panitumumab", name: "Panitumumab (Vectibix)", class: "Monoclonal — anti-EGFR",
    standardDose: "6 mg/kg IV q2wk (RAS wild-type CRC)" },
  { id: "ramucirumab", name: "Ramucirumab (Cyramza)", class: "Monoclonal — anti-VEGFR2",
    standardDose: "8 mg/kg IV q2wk (gastric, HCC)" },
  { id: "nivolumab", name: "Nivolumab (Opdivo / Opdyta)", class: "Immunotherapy — anti-PD-1",
    standardDose: "240 mg IV q2wk or 480 mg q4wk — immune-related adverse events (thyroid, colitis, pneumonitis, hepatitis) need steroid protocols, not dose reduction" },
  { id: "pembrolizumab", name: "Pembrolizumab (Keytruda)", class: "Immunotherapy — anti-PD-1",
    standardDose: "200 mg IV q3wk or 400 mg q6wk (same immune-related toxicity vigilance)" },
  { id: "atezolizumab", name: "Atezolizumab (Tecentriq)", class: "Immunotherapy — anti-PD-L1",
    standardDose: "1200 mg IV q3wk" },
  { id: "durvalumab", name: "Durvalumab (Imfinzi)", class: "Immunotherapy — anti-PD-L1",
    standardDose: "10 mg/kg IV q2wk (consolidation after chemoRT in stage III NSCLC)" },
  { id: "ipilimumab", name: "Ipilimumab (Yervoy)", class: "Immunotherapy — anti-CTLA-4",
    standardDose: "3 mg/kg IV q3wk ×4 (highest immune-toxicity rate — colitis, hypophysitis)" },
  { id: "daratumumab", name: "Daratumumab (Darzalex)", class: "Monoclonal — anti-CD38",
    standardDose: "16 mg/kg IV weekly→q2wk→monthly (myeloma); interferes with blood cross-matching — inform blood bank" },

  // ============ ONCOLOGY — hormonal agents ============
  { id: "fulvestrant", name: "Fulvestrant (Faslodex)", class: "Hormonal — ER degrader",
    standardDose: "500 mg IM days 1, 15, 29 then monthly (ER+ metastatic breast)" },
  { id: "exemestane", name: "Exemestane (Aromasin / X-Trane)", class: "Hormonal — aromatase inhibitor",
    standardDose: "25 mg PO OD after food (postmenopausal ER+ breast)" },
  { id: "bicalutamide", name: "Bicalutamide (Calutide)", class: "Hormonal — antiandrogen",
    standardDose: "50 mg PO OD with LHRH agonist (prostate)" },
  { id: "flutamide", name: "Flutamide (Cytomid)", class: "Hormonal — antiandrogen",
    standardDose: "250 mg PO TID (hepatotoxicity — LFT monitoring)" },
  { id: "enzalutamide", name: "Enzalutamide (Xtandi / Obnyx)", class: "Hormonal — androgen receptor inhibitor",
    standardDose: "160 mg PO OD (seizure threshold lowered; many CYP interactions)" },
  { id: "abiraterone", name: "Abiraterone (Zytiga / Abirapro)", class: "Hormonal — CYP17 inhibitor",
    standardDose: "1000 mg PO OD empty stomach WITH prednisolone 5–10 mg (hypertension, hypokalemia, fluid retention)" },
  { id: "apalutamide", name: "Apalutamide (Erleada)", class: "Hormonal — androgen receptor inhibitor",
    standardDose: "240 mg PO OD (rash, hypothyroidism, fracture risk)" },
  { id: "leuprolide", name: "Leuprolide (Lupride / Eligard)", class: "Hormonal — GnRH agonist",
    standardDose: "3.75 mg IM monthly or 11.25 mg q3mo (initial testosterone flare — cover with antiandrogen in metastatic prostate)" },
  { id: "goserelin", name: "Goserelin (Zoladex)", class: "Hormonal — GnRH agonist",
    standardDose: "3.6 mg SC implant monthly or 10.8 mg q3mo" },
  { id: "degarelix", name: "Degarelix (Firmagon)", class: "Hormonal — GnRH antagonist",
    standardDose: "240 mg SC load then 80 mg monthly (no flare — preferred with cord compression risk)" },
  { id: "megestrol", name: "Megestrol acetate (Megace)", class: "Hormonal — progestin",
    standardDose: "160–320 mg/day PO (appetite/cachexia; endometrial cancer); VTE risk" },

  // ============ ONCOLOGY — myeloma / APL / other ============
  { id: "bortezomib", name: "Bortezomib (Velcade / Bortenat)", class: "Chemo — proteasome inhibitor",
    standardDose: "1.3 mg/m² SC days 1, 4, 8, 11 per cycle (SC route halves neuropathy; herpes zoster prophylaxis with acyclovir)" },
  { id: "carfilzomib", name: "Carfilzomib (Kyprolis)", class: "Chemo — proteasome inhibitor",
    standardDose: "20→27–56 mg/m² IV per protocol (cardiac failure risk — baseline echo)" },
  { id: "ixazomib", name: "Ixazomib (Ninlaro)", class: "Chemo — oral proteasome inhibitor",
    standardDose: "4 mg PO days 1, 8, 15 q28d empty stomach" },
  { id: "lenalidomide", name: "Lenalidomide (Lenalid)", class: "Immunomodulator (IMiD)",
    standardDose: "Myeloma: 25 mg PO days 1–21 q28d with dexamethasone; MANDATORY VTE prophylaxis (aspirin/LMWH); teratogenic",
    renalAdjustmentLimit: 60, renalNote: "10 mg if CrCl 30–60; 15 mg alternate days < 30." },
  { id: "thalidomide", name: "Thalidomide (Thalix)", class: "Immunomodulator (IMiD)",
    standardDose: "50–200 mg PO at night (severe teratogen; neuropathy, sedation, VTE prophylaxis needed)" },
  { id: "pomalidomide", name: "Pomalidomide (Pomalid)", class: "Immunomodulator (IMiD)",
    standardDose: "4 mg PO days 1–21 q28d (relapsed myeloma); VTE prophylaxis" },
  { id: "tretinoin-atra", name: "Tretinoin / ATRA (Vesanoid)", class: "Chemo — differentiating agent",
    standardDose: "APL: 45 mg/m²/day PO divided until remission (differentiation syndrome — dexamethasone at first sign)" },
  { id: "arsenic-trioxide", name: "Arsenic trioxide (Arsenox)", class: "Chemo — differentiating agent",
    standardDose: "APL: 0.15 mg/kg/day IV (QT prolongation — keep K > 4, Mg > 1.8, ECG twice weekly)" },
  { id: "asparaginase", name: "L-Asparaginase (Leunase)", class: "Chemo — enzyme",
    standardDose: "ALL protocols: 6,000–10,000 IU/m² IM per schedule (pancreatitis, thrombosis, anaphylaxis)" },

  // ============ ONCOLOGY — supportive care ============
  { id: "filgrastim", name: "Filgrastim (Grafeel / Neupogen)", class: "Supportive — G-CSF",
    standardDose: "5 µg/kg/day SC starting 24–72 h after chemo until ANC recovery" },
  { id: "pegfilgrastim", name: "Pegfilgrastim (Neulastim)", class: "Supportive — long-acting G-CSF",
    standardDose: "6 mg SC once per cycle, ≥ 24 h after chemo" },
  { id: "erythropoietin", name: "Erythropoietin alfa (Eprex / Wepox)", class: "Supportive — ESA",
    standardDose: "CKD/chemo anemia: 50–100 IU/kg SC 3×/week; target Hb ≤ 11 g/dL (thrombosis above)" },
  { id: "mesna", name: "Mesna (Uromitexan)", class: "Supportive — uroprotectant",
    standardDose: "60–100% of ifosfamide/cyclophosphamide dose divided at 0, 4, 8 h (hemorrhagic cystitis prevention)" },
  { id: "leucovorin", name: "Leucovorin / folinic acid (Calcium Leucovorin)", class: "Supportive — folate rescue",
    standardDose: "Methotrexate rescue: 15 mg/m² q6h ×10 starting 24 h after HD-MTX; 5-FU modulation per FOLFOX" },
  { id: "rasburicase", name: "Rasburicase (Rasburnat)", class: "Supportive — urate oxidase",
    standardDose: "Tumour lysis: 0.2 mg/kg IV OD ×1–5 days (contraindicated in G6PD deficiency)" },
  { id: "aprepitant", name: "Aprepitant (Aprecap)", class: "Supportive — NK1 antiemetic",
    standardDose: "125 mg PO day 1, 80 mg days 2–3 with 5-HT3 + dexamethasone (highly emetogenic chemo)" },
  { id: "palonosetron", name: "Palonosetron (Palnox)", class: "Supportive — 5-HT3 antiemetic",
    standardDose: "0.25 mg IV single dose before chemo" },
  { id: "granisetron", name: "Granisetron (Granicip)", class: "Supportive — 5-HT3 antiemetic",
    standardDose: "1–2 mg PO or 1 mg IV before chemo" },
  { id: "zoledronic-acid", name: "Zoledronic acid (Zoldria / Zometa)", class: "Bisphosphonate (IV)",
    standardDose: "Bone mets: 4 mg IV q3–4wk; osteoporosis: 5 mg IV yearly — dental check first (ONJ risk)",
    renalAdjustmentLimit: 35, renalNote: "Reduce dose CrCl 35–60; avoid < 35." },
  { id: "denosumab", name: "Denosumab (Xgeva / Prolia)", class: "Monoclonal — RANKL inhibitor",
    standardDose: "Bone mets: 120 mg SC q4wk; osteoporosis: 60 mg SC q6mo (hypocalcemia — check Ca/vit D first; usable in renal failure)" },

  // ============ ANTIBIOTICS — remaining common agents ============
  { id: "penicillin-v", name: "Penicillin V (Pentids)", class: "Penicillin antibiotic",
    standardDose: "250–500 mg PO QID; rheumatic fever prophylaxis 250 mg BID" },
  { id: "benzathine-penicillin", name: "Benzathine penicillin G (Pencom)", class: "Penicillin antibiotic (IM depot)",
    standardDose: "1.2 MU IM (RF prophylaxis q3–4wk; syphilis 2.4 MU per stage)" },
  { id: "ampicillin", name: "Ampicillin", class: "Penicillin antibiotic",
    standardDose: "500 mg–2 g IV q6h (listeria, enterococcus, neonatal sepsis regimens)",
    renalAdjustmentLimit: 30, renalNote: "Extend interval CrCl < 30." },
  { id: "cloxacillin", name: "Cloxacillin (Klox)", class: "Anti-staphylococcal penicillin",
    standardDose: "500 mg PO QID or 1–2 g IV q4–6h (MSSA)" },
  { id: "cefaclor", name: "Cefaclor (Distaclor)", class: "2nd-generation cephalosporin",
    standardDose: "250–500 mg PO TID" },
  { id: "cefoperazone-sulbactam", name: "Cefoperazone-Sulbactam (Magnex)", class: "3rd-gen cephalosporin + BLI",
    standardDose: "1.5–3 g IV q12h (biliary/hospital infections); vitamin K watch (hypoprothrombinemia)" },
  { id: "ceftazidime-avibactam", name: "Ceftazidime-Avibactam (Zavicefta)", class: "Reserve antibiotic — BL/BLI",
    standardDose: "2.5 g IV q8h over 2 h (carbapenem-resistant Enterobacterales)",
    renalAdjustmentLimit: 50, renalNote: "Dose-reduce stepwise below CrCl 50." },
  { id: "aztreonam", name: "Aztreonam", class: "Monobactam antibiotic",
    standardDose: "1–2 g IV q8h (gram-negative cover in severe penicillin allergy)",
    renalAdjustmentLimit: 30, renalNote: "Halve dose CrCl 10–30." },
  { id: "roxithromycin", name: "Roxithromycin (Roxid)", class: "Macrolide antibiotic",
    standardDose: "150 mg PO BID before food" },
  { id: "minocycline", name: "Minocycline (Cynomycin)", class: "Tetracycline antibiotic",
    standardDose: "100 mg PO BID (acne, atypicals; vestibular side effects)" },
  { id: "chloramphenicol", name: "Chloramphenicol", class: "Antibiotic (reserve)",
    standardDose: "50–100 mg/kg/day IV divided q6h (enteric fever alternative; aplastic anemia risk)" },
  { id: "dapsone", name: "Dapsone", class: "Antileprotic / PCP alternative",
    standardDose: "100 mg PO OD (leprosy MDT; dermatitis herpetiformis) — check G6PD first" },
  { id: "clofazimine", name: "Clofazimine (Hansepran)", class: "Antileprotic",
    standardDose: "50 mg OD + 300 mg monthly supervised (MB-MDT); skin discolouration" },
  { id: "rifabutin", name: "Rifabutin", class: "Antitubercular / MAC",
    standardDose: "300 mg PO OD (rifampicin substitute with ART interactions); uveitis at high dose" },
  { id: "bedaquiline", name: "Bedaquiline (Sirturo)", class: "Antitubercular — MDR-TB",
    standardDose: "400 mg OD ×2wk then 200 mg 3×/week ×22wk with food (QT — ECG monthly; only in regimen, never alone)" },
  { id: "delamanid", name: "Delamanid (Deltyba)", class: "Antitubercular — MDR-TB",
    standardDose: "100 mg PO BID ×24wk (QT monitoring)" },
  { id: "cycloserine", name: "Cycloserine (Coxerin)", class: "Antitubercular — second line",
    standardDose: "250 mg BID–TID (10–15 mg/kg/day) with pyridoxine 50 mg per 250 mg (psychiatric toxicity)",
    renalAdjustmentLimit: 50, renalNote: "Accumulates — reduce and level-monitor in renal impairment." },
  { id: "ethionamide", name: "Ethionamide (Ethide)", class: "Antitubercular — second line",
    standardDose: "15–20 mg/kg/day (max 1 g) in divided doses (GI intolerance, hypothyroidism — TSH q3mo)" },
  { id: "capreomycin", name: "Capreomycin", class: "Antitubercular — injectable",
    standardDose: "15 mg/kg IM OD (oto/nephrotoxic — audiometry and creatinine monitoring)",
    renalAdjustmentLimit: 60, renalNote: "Extend interval; avoid if alternatives exist." },
  { id: "nitazoxanide", name: "Nitazoxanide (Nizonide)", class: "Antiparasitic / antidiarrheal",
    standardDose: "500 mg PO BID ×3 days with food (giardia, crypto)" },
  { id: "secnidazole", name: "Secnidazole (Secnil)", class: "Nitroimidazole",
    standardDose: "2 g PO single dose (amoebiasis, BV outside pregnancy)" },
  { id: "ornidazole", name: "Ornidazole (Ornof component)", class: "Nitroimidazole",
    standardDose: "500 mg PO BID ×5 days" },

  // ============ ANTIVIRALS — HCV / influenza / COVID ============
  { id: "molnupiravir", name: "Molnupiravir (Molflu)", class: "Antiviral — COVID-19",
    standardDose: "800 mg PO BID ×5 days within 5 days of onset (avoid in pregnancy)" },
  { id: "nirmatrelvir-ritonavir", name: "Nirmatrelvir-Ritonavir (Paxzen)", class: "Antiviral — COVID-19",
    standardDose: "300/100 mg PO BID ×5 days (major CYP3A interactions — check every co-medication)",
    renalAdjustmentLimit: 60, renalNote: "150/100 mg BID if eGFR 30–60; avoid < 30." },
  { id: "ribavirin", name: "Ribavirin (Ribavin)", class: "Antiviral",
    standardDose: "Weight-based 1000–1200 mg/day divided (hemolytic anemia — Hb monitoring; teratogen both partners)",
    renalAdjustmentLimit: 50, renalNote: "Avoid if CrCl < 50." },
  { id: "sofosbuvir", name: "Sofosbuvir (Hepcinat / MyHep)", class: "Antiviral — HCV NS5B",
    standardDose: "400 mg PO OD ×12wk in combination (avoid with amiodarone — severe bradycardia)",
    renalAdjustmentLimit: 30, renalNote: "Use with caution below eGFR 30 (now generally permitted; monitor)." },
  { id: "daclatasvir", name: "Daclatasvir (Natdac)", class: "Antiviral — HCV NS5A",
    standardDose: "60 mg PO OD with sofosbuvir ×12wk" },
  { id: "sofosbuvir-velpatasvir", name: "Sofosbuvir-Velpatasvir (Velpanat / Epclusa)", class: "Antiviral — pan-genotypic HCV",
    standardDose: "400/100 mg PO OD ×12wk (separate from PPIs/antacids — velpatasvir needs acid)" },
  { id: "ledipasvir-sofosbuvir", name: "Ledipasvir-Sofosbuvir (Hepcinat-LP)", class: "Antiviral — HCV",
    standardDose: "90/400 mg PO OD ×12wk (genotype 1)" },
  { id: "peginterferon-alfa", name: "Peginterferon alfa-2a (Pegasys)", class: "Antiviral — interferon",
    standardDose: "180 µg SC weekly (HBV; depression/cytopenias monitoring)" },
  { id: "favipiravir", name: "Favipiravir (Fabiflu)", class: "Antiviral",
    standardDose: "1800 mg BID day 1 then 800 mg BID (limited evidence; uric acid rise; teratogen)" },
  { id: "zanamivir", name: "Zanamivir (Relenza)", class: "Antiviral — influenza",
    standardDose: "10 mg (2 inhalations) BID ×5 days (bronchospasm caution in asthma/COPD)" },

  // ============ ANTIMALARIALS & antiparasitics ============
  { id: "chloroquine", name: "Chloroquine (Lariago)", class: "Antimalarial",
    standardDose: "P. vivax: 25 mg base/kg over 3 days (600, 600, 300 mg); retinopathy with chronic use" },
  { id: "primaquine", name: "Primaquine", class: "Antimalarial — radical cure",
    standardDose: "Vivax: 0.25 mg/kg/day ×14 days AFTER G6PD testing; falciparum gametocide 0.25 mg/kg single dose" },
  { id: "artesunate", name: "Artesunate (Falcigo)", class: "Antimalarial — artemisinin",
    standardDose: "Severe malaria: 2.4 mg/kg IV at 0, 12, 24 h then OD (3 mg/kg if < 20 kg); watch delayed hemolysis at day 7–14" },
  { id: "artemether-lumefantrine", name: "Artemether-Lumefantrine (Lumerax / Coartem)", class: "Antimalarial — ACT",
    standardDose: "80/480 mg PO BID ×3 days with fatty food (uncomplicated falciparum)" },
  { id: "quinine", name: "Quinine", class: "Antimalarial",
    standardDose: "600 mg PO TID ×7 days with doxycycline (cinchonism; hypoglycemia in pregnancy)",
    renalAdjustmentLimit: 30, renalNote: "Reduce frequency in severe renal impairment." },
  { id: "mefloquine", name: "Mefloquine (Larium)", class: "Antimalarial — prophylaxis",
    standardDose: "250 mg PO weekly from 2 wk before travel (neuropsychiatric contraindications)" },
  { id: "praziquantel", name: "Praziquantel (Distocide)", class: "Anthelmintic",
    standardDose: "Schistosomiasis 40 mg/kg divided ×1 day; tapeworm 10–20 mg/kg single dose" },
  { id: "diethylcarbamazine", name: "Diethylcarbamazine (Hetrazan)", class: "Antifilarial",
    standardDose: "6 mg/kg/day ×12 days (lymphatic filariasis)" },
  { id: "mebendazole", name: "Mebendazole (Mebex)", class: "Anthelmintic",
    standardDose: "100 mg PO BID ×3 days or 500 mg single dose" },
  { id: "miltefosine", name: "Miltefosine (Impavido)", class: "Antileishmanial",
    standardDose: "50 mg PO BID ×28 days (kala-azar; teratogen — contraception 5 months)" },

  // ============ CARDIOVASCULAR — remaining common agents ============
  { id: "perindopril", name: "Perindopril (Coversyl)", class: "ACE inhibitor",
    standardDose: "4–8 mg PO OD", renalAdjustmentLimit: 30, renalNote: "Reduce dose; monitor K and creatinine." },
  { id: "lisinopril", name: "Lisinopril (Listril)", class: "ACE inhibitor",
    standardDose: "10–40 mg PO OD", renalAdjustmentLimit: 30, renalNote: "Start low; monitor K/creatinine." },
  { id: "captopril", name: "Captopril (Aceten)", class: "ACE inhibitor",
    standardDose: "25–50 mg PO TID (also sublingual in hypertensive urgency practice)" },
  { id: "valsartan", name: "Valsartan (Valzaar)", class: "ARB",
    standardDose: "80–160 mg PO OD–BID" },
  { id: "irbesartan", name: "Irbesartan (Irovel)", class: "ARB",
    standardDose: "150–300 mg PO OD" },
  { id: "azilsartan", name: "Azilsartan (Azilday)", class: "ARB",
    standardDose: "40–80 mg PO OD" },
  { id: "nebivolol", name: "Nebivolol (Nebicard)", class: "Beta-blocker (vasodilating)",
    standardDose: "2.5–10 mg PO OD" },
  { id: "labetalol", name: "Labetalol (Lobet)", class: "Alpha-beta blocker",
    standardDose: "100–400 mg PO BID; IV 20→40→80 mg boluses in hypertensive emergency/pregnancy" },
  { id: "propranolol", name: "Propranolol (Ciplar / Inderal)", class: "Beta-blocker (non-selective)",
    standardDose: "10–40 mg PO TID; migraine prophylaxis 40–80 mg BID; portal HTN titrate to HR 55–60" },
  { id: "ivabradine", name: "Ivabradine (Ivabrad)", class: "If-channel inhibitor",
    standardDose: "5–7.5 mg PO BID (HFrEF/angina in sinus rhythm with HR ≥ 70)" },
  { id: "ranolazine", name: "Ranolazine (Ranozex)", class: "Anti-anginal",
    standardDose: "500–1000 mg PO BID (QT caution; CYP3A interactions)" },
  { id: "eplerenone", name: "Eplerenone (Eptus)", class: "MRA diuretic",
    standardDose: "25–50 mg PO OD (post-MI HF; less gynecomastia than spironolactone)",
    renalAdjustmentLimit: 30, renalNote: "Avoid CrCl < 30; monitor K." },
  { id: "indapamide", name: "Indapamide (Natrilix)", class: "Thiazide-like diuretic",
    standardDose: "1.5 mg SR PO OD morning (hyponatremia watch in elderly)" },
  { id: "methyldopa", name: "Methyldopa (Alphadopa)", class: "Central antihypertensive",
    standardDose: "250 mg PO BID–TID, max 3 g/day (pregnancy hypertension mainstay)" },
  { id: "hydralazine", name: "Hydralazine", class: "Vasodilator",
    standardDose: "25–100 mg PO BID–TID (with nitrate in HF); IV 5–10 mg in severe pregnancy HTN" },
  { id: "minoxidil-oral", name: "Minoxidil oral (Lonitab)", class: "Vasodilator (resistant HTN)",
    standardDose: "5–40 mg/day with beta-blocker + loop diuretic (reflex tachycardia, fluid retention)" },
  { id: "flecainide", name: "Flecainide", class: "Antiarrhythmic (Ic)",
    standardDose: "Pill-in-pocket 200–300 mg; maintenance 50–100 mg BID (only in structurally normal heart)" },
  { id: "propafenone", name: "Propafenone", class: "Antiarrhythmic (Ic)",
    standardDose: "150–300 mg PO TID (structurally normal heart only)" },
  { id: "dronedarone", name: "Dronedarone (Multaq)", class: "Antiarrhythmic (III)",
    standardDose: "400 mg PO BID with meals (contraindicated in HF and permanent AF)" },
  { id: "mexiletine", name: "Mexiletine", class: "Antiarrhythmic (Ib)",
    standardDose: "150–200 mg PO q8h (also myotonia)" },

  // ============ LIPIDS / ANTICOAGULATION / THROMBOLYSIS ============
  { id: "pravastatin", name: "Pravastatin", class: "Statin",
    standardDose: "20–40 mg PO at night (fewest CYP interactions)" },
  { id: "pitavastatin", name: "Pitavastatin (Pivasta)", class: "Statin",
    standardDose: "1–4 mg PO OD" },
  { id: "evolocumab", name: "Evolocumab (Repatha)", class: "PCSK9 inhibitor",
    standardDose: "140 mg SC q2wk or 420 mg monthly" },
  { id: "edoxaban", name: "Edoxaban (Lixiana)", class: "DOAC (factor Xa inhibitor)",
    standardDose: "60 mg PO OD (30 mg if CrCl 15–50, ≤ 60 kg, or strong P-gp inhibitor)",
    renalAdjustmentLimit: 50, renalNote: "30 mg OD CrCl 15–50; avoid < 15 AND avoid if CrCl > 95 in AF." },
  { id: "heparin", name: "Heparin unfractionated", class: "Anticoagulant (IV)",
    standardDose: "80 U/kg bolus then 18 U/kg/h, titrate to aPTT 1.5–2.5×; HIT watch day 5–10" },
  { id: "dalteparin", name: "Dalteparin (Fragmin)", class: "LMWH",
    standardDose: "Treatment 200 IU/kg SC OD; prophylaxis 5000 IU OD",
    renalAdjustmentLimit: 30, renalNote: "Prefer UFH or anti-Xa monitoring CrCl < 30." },
  { id: "streptokinase", name: "Streptokinase (STPase)", class: "Thrombolytic",
    standardDose: "STEMI: 1.5 MU IV over 60 min (never repeat between 5 days and 12 months — antibodies)" },
  { id: "alteplase", name: "Alteplase (Actilyse)", class: "Thrombolytic (tPA)",
    standardDose: "Stroke: 0.9 mg/kg (max 90 mg), 10% bolus + rest over 60 min within 4.5 h; STEMI accelerated 100 mg regimen" },
  { id: "tenecteplase", name: "Tenecteplase (Elaxim)", class: "Thrombolytic (single bolus)",
    standardDose: "Weight-banded 30–50 mg IV single bolus (STEMI; 0.25 mg/kg in stroke trials)" },
  { id: "cilostazol", name: "Cilostazol (Pletoz)", class: "Antiplatelet / PDE3 inhibitor",
    standardDose: "100 mg PO BID half-hour before food (claudication); contraindicated in HF" },
  { id: "dipyridamole", name: "Dipyridamole (Persantin)", class: "Antiplatelet",
    standardDose: "ER 200 mg BID with aspirin (stroke secondary prevention)" },

  // ============ DIABETES / ENDOCRINE ============
  { id: "glipizide", name: "Glipizide (Glynase)", class: "Sulfonylurea",
    standardDose: "2.5–10 mg PO before breakfast" },
  { id: "semaglutide", name: "Semaglutide (Rybelsus / Ozempic)", class: "GLP-1 agonist",
    standardDose: "Oral 3→7→14 mg OD fasting with sips of water; SC 0.25→1–2 mg weekly (pancreatitis, gastroparesis caution)" },
  { id: "liraglutide", name: "Liraglutide (Victoza)", class: "GLP-1 agonist",
    standardDose: "0.6→1.2–1.8 mg SC OD" },
  { id: "dulaglutide", name: "Dulaglutide (Trulicity)", class: "GLP-1 agonist",
    standardDose: "0.75–1.5 mg SC weekly" },
  { id: "insulin-aspart", name: "Insulin aspart (NovoRapid)", class: "Rapid-acting insulin",
    standardDose: "Individualized; with meals, onset 10–20 min" },
  { id: "insulin-lispro", name: "Insulin lispro (Humalog)", class: "Rapid-acting insulin",
    standardDose: "Individualized; with meals" },
  { id: "insulin-degludec", name: "Insulin degludec (Tresiba)", class: "Ultra-long basal insulin",
    standardDose: "Individualized OD (flexible timing; lowest nocturnal hypo rate)" },
  { id: "insulin-nph", name: "Insulin NPH (Insulatard / Huminsulin N)", class: "Intermediate insulin",
    standardDose: "Individualized OD–BID (pregnancy basal insulin of choice where glargine unavailable)" },
  { id: "carbimazole", name: "Carbimazole (Neo-Mercazole)", class: "Antithyroid",
    standardDose: "10–40 mg PO OD titrated (agranulocytosis warning — CBC if fever/sore throat; avoid 1st trimester)" },
  { id: "propylthiouracil", name: "Propylthiouracil (PTU)", class: "Antithyroid",
    standardDose: "50–150 mg PO q8h (1st trimester and thyroid storm preferences; hepatotoxicity)" },
  { id: "liothyronine", name: "Liothyronine (T3)", class: "Thyroid hormone",
    standardDose: "5–20 µg/day (myxedema protocols; short half-life)" },
  { id: "teriparatide", name: "Teriparatide (Terifrac)", class: "PTH analogue",
    standardDose: "20 µg SC OD, max 2 years lifetime (severe osteoporosis)" },
  { id: "risedronate", name: "Risedronate (Risofos)", class: "Bisphosphonate (oral)",
    standardDose: "35 mg PO weekly, fasting, upright 30 min",
    renalAdjustmentLimit: 30, renalNote: "Avoid CrCl < 30." },
  { id: "ibandronate", name: "Ibandronate (Idrofos)", class: "Bisphosphonate",
    standardDose: "150 mg PO monthly or 3 mg IV q3mo",
    renalAdjustmentLimit: 30, renalNote: "Avoid CrCl < 30." },
  { id: "cinacalcet", name: "Cinacalcet (Cinabon)", class: "Calcimimetic",
    standardDose: "30–90 mg PO OD with food (secondary hyperparathyroidism on dialysis; hypocalcemia watch)" },
  { id: "desmopressin", name: "Desmopressin (Minirin)", class: "Vasopressin analogue",
    standardDose: "Central DI: 0.1–0.2 mg PO BID–TID or 10 µg intranasal; hyponatremia — the key toxicity",
    geriatricGuidelines: [{ type: "Beers", ruleDescription: "High hyponatremia risk for nocturia in older adults.", recommendation: "Avoid for nocturia in age ≥ 65" }] },
  { id: "fludrocortisone", name: "Fludrocortisone (Floricot)", class: "Mineralocorticoid",
    standardDose: "0.05–0.2 mg PO OD (Addison, orthostatic hypotension; hypokalemia/edema watch)" },
  { id: "cabergoline", name: "Cabergoline (Cabgolin)", class: "Dopamine agonist",
    standardDose: "0.25–1 mg PO twice weekly (prolactinoma); echo for valvopathy at high cumulative dose" },
  { id: "bromocriptine", name: "Bromocriptine (Proctinal)", class: "Dopamine agonist",
    standardDose: "1.25–2.5 mg OD titrated (prolactinoma, acromegaly adjunct)" },
  { id: "octreotide", name: "Octreotide (Sandostatin)", class: "Somatostatin analogue",
    standardDose: "Variceal bleed: 50 µg IV bolus then 50 µg/h ×3–5 days; acromegaly/NET: LAR 20–30 mg IM monthly" },
  { id: "terlipressin", name: "Terlipressin (Glypressin)", class: "Vasopressin analogue",
    standardDose: "Variceal bleed: 2 mg IV q4h then 1 mg q4h; HRS-AKI: 1 mg q6h (ischemia watch)" },

  // ============ NEUROLOGY / PSYCHIATRY ============
  { id: "carbamazepine", name: "Carbamazepine (Tegretol / Zeptol)", class: "Antiepileptic",
    standardDose: "200 mg BID → 400–600 mg BID CR (trigeminal neuralgia first-line); HLA-B*1502 screening in Asian ancestry (SJS); many enzyme interactions",
    geriatricGuidelines: [{ type: "Beers", ruleDescription: "SIADH/hyponatremia risk in older adults.", recommendation: "Monitor sodium; use cautiously" }] },
  { id: "oxcarbazepine", name: "Oxcarbazepine (Oxetol)", class: "Antiepileptic",
    standardDose: "300 mg BID → 600–1200 mg BID (hyponatremia more than carbamazepine)" },
  { id: "lamotrigine", name: "Lamotrigine (Lamitor)", class: "Antiepileptic / mood stabilizer",
    standardDose: "SLOW titration 25 mg OD ×2wk → 50 → target 100–200 mg BID (rash/SJS with fast titration; halve schedule with valproate)" },
  { id: "phenobarbital", name: "Phenobarbital (Gardenal)", class: "Antiepileptic — barbiturate",
    standardDose: "60–180 mg PO at night; status: 20 mg/kg IV loading",
    geriatricGuidelines: [{ type: "Beers", ruleDescription: "High dependence, sedation, falls.", recommendation: "Avoid in older adults" }] },
  { id: "lacosamide", name: "Lacosamide (Lacosam)", class: "Antiepileptic",
    standardDose: "50 mg BID → 100–200 mg BID (PR prolongation — ECG in cardiac disease)" },
  { id: "zonisamide", name: "Zonisamide (Zonisep)", class: "Antiepileptic",
    standardDose: "100–300 mg OD (renal stones, oligohidrosis in children)" },
  { id: "clobazam", name: "Clobazam (Frisium)", class: "Benzodiazepine antiepileptic",
    standardDose: "5–10 mg at night → max 60 mg/day (adjunct; catamenial cover)" },
  { id: "brivaracetam", name: "Brivaracetam (Brivasure)", class: "Antiepileptic",
    standardDose: "50–100 mg BID (levetiracetam alternative with less irritability)" },
  { id: "perampanel", name: "Perampanel (Fycompa)", class: "Antiepileptic",
    standardDose: "2 mg at night → 4–12 mg (psychiatric/behavioral effects warning)" },
  { id: "vigabatrin", name: "Vigabatrin (Sabril)", class: "Antiepileptic",
    standardDose: "Infantile spasms: 50–150 mg/kg/day (permanent visual field defects — field monitoring)" },
  { id: "ropinirole", name: "Ropinirole (Ropark)", class: "Dopamine agonist (Parkinson/RLS)",
    standardDose: "PD: 0.25 mg TID titrated; RLS: 0.25–4 mg 2 h before bed (impulse-control disorders, sleep attacks)" },
  { id: "rasagiline", name: "Rasagiline (Rasalect)", class: "MAO-B inhibitor",
    standardDose: "1 mg PO OD (serotonin syndrome caution with SSRIs/tramadol/pethidine)" },
  { id: "selegiline", name: "Selegiline (Eldepryl)", class: "MAO-B inhibitor",
    standardDose: "5 mg with breakfast and lunch (insomnia if evening dosing)" },
  { id: "entacapone", name: "Entacapone (Comtan)", class: "COMT inhibitor",
    standardDose: "200 mg with EACH levodopa dose, max 8×/day (urine discolouration)" },
  { id: "safinamide", name: "Safinamide (Onstryv)", class: "MAO-B inhibitor",
    standardDose: "50–100 mg PO OD add-on to levodopa" },
  { id: "rivastigmine", name: "Rivastigmine (Exelon / Rivamer)", class: "Cholinesterase inhibitor",
    standardDose: "1.5 mg BID → 6 mg BID, or patch 4.6→9.5 mg/24 h (dementia incl. Lewy body/PDD)" },
  { id: "galantamine", name: "Galantamine (Galamer)", class: "Cholinesterase inhibitor",
    standardDose: "8 → 16–24 mg/day ER" },
  { id: "fluvoxamine", name: "Fluvoxamine (Fluvoxin)", class: "SSRI antidepressant",
    standardDose: "50–300 mg/day (OCD; strong CYP1A2 inhibitor — theophylline, clozapine interactions)" },
  { id: "vortioxetine", name: "Vortioxetine (Brintellix)", class: "Antidepressant (multimodal)",
    standardDose: "5–20 mg PO OD" },
  { id: "bupropion", name: "Bupropion (Bupron)", class: "NDRI antidepressant",
    standardDose: "SR 150 mg OD → BID (contraindicated in seizure disorder and eating disorders; smoking cessation aid)" },
  { id: "agomelatine", name: "Agomelatine (Valdoxan)", class: "Melatonergic antidepressant",
    standardDose: "25–50 mg at bedtime (LFTs at baseline, 3, 6, 12, 24 wk)" },
  { id: "buspirone", name: "Buspirone (Buspin)", class: "Anxiolytic (non-benzo)",
    standardDose: "5 mg TID → 20–30 mg/day divided (takes 2–4 wk; no dependence)" },
  { id: "lurasidone", name: "Lurasidone (Latuda / Lurasid)", class: "Atypical antipsychotic",
    standardDose: "40–120 mg OD WITH ≥ 350 kcal food (bipolar depression; metabolically clean)" },
  { id: "ziprasidone", name: "Ziprasidone (Zipsydon)", class: "Atypical antipsychotic",
    standardDose: "20–80 mg BID with food (QT prolongation)" },
  { id: "paliperidone", name: "Paliperidone (Palido)", class: "Atypical antipsychotic",
    standardDose: "3–12 mg OD ER; LAI monthly options",
    renalAdjustmentLimit: 50, renalNote: "Start 3 mg alternate-day dosing schedule CrCl < 50." },
  { id: "sumatriptan", name: "Sumatriptan (Suminat)", class: "Triptan",
    standardDose: "50–100 mg PO at onset, may repeat after 2 h (max 200 mg/day); avoid in CAD/uncontrolled HTN" },
  { id: "rizatriptan", name: "Rizatriptan (Rizact)", class: "Triptan",
    standardDose: "10 mg PO at onset (5 mg with propranolol)" },
  { id: "melatonin", name: "Melatonin (Meloset)", class: "Sleep aid",
    standardDose: "3–10 mg 30–60 min before bed (preferred over Z-drugs in elderly)" },
  { id: "naloxone", name: "Naloxone (Narcotan-N)", class: "Opioid antidote",
    standardDose: "0.4–2 mg IV/IM/IN, repeat q2–3 min (short half-life — infusion for long-acting opioid overdose)" },
  { id: "flumazenil", name: "Flumazenil", class: "Benzodiazepine antidote",
    standardDose: "0.2 mg IV over 30 s, repeat to max 1 mg (seizure risk in dependence/TCA co-ingestion)" },
  { id: "neostigmine", name: "Neostigmine", class: "Cholinesterase inhibitor",
    standardDose: "0.5–2.5 mg IV/SC (with glycopyrrolate); myasthenia 15–30 mg PO q4–6h" },
  { id: "pyridostigmine", name: "Pyridostigmine (Distinon)", class: "Cholinesterase inhibitor",
    standardDose: "Myasthenia: 30–120 mg PO q4–8h timed around meals and activity" },

  // ============ RESPIRATORY / ENT ============
  { id: "budesonide-formoterol", name: "Budesonide-Formoterol (Foracort)", class: "ICS-LABA inhaler",
    standardDose: "100/6–400/12 µg BID; also reliever in MART regimens" },
  { id: "salmeterol-fluticasone", name: "Salmeterol-Fluticasone (Seroflo)", class: "ICS-LABA inhaler",
    standardDose: "25/125–25/250 µg 2 puffs BID (never LABA alone in asthma)" },
  { id: "glycopyrronium", name: "Glycopyrronium inhaled (Glybrez)", class: "LAMA inhaler",
    standardDose: "50 µg OD inhaled (COPD)" },
  { id: "roflumilast", name: "Roflumilast (Rofair)", class: "PDE4 inhibitor",
    standardDose: "500 µg PO OD (severe COPD with exacerbations; weight loss, psychiatric effects)" },
  { id: "ambroxol", name: "Ambroxol (Mucolite)", class: "Mucolytic",
    standardDose: "30 mg PO TID" },
  { id: "dextromethorphan", name: "Dextromethorphan (various)", class: "Antitussive",
    standardDose: "10–20 mg q4h PRN (serotonin syndrome with MAOIs/SSRIs)" },
  { id: "codeine", name: "Codeine", class: "Opioid antitussive/analgesic",
    standardDose: "15–30 mg q6h PRN (contraindicated < 12 years and breastfeeding — CYP2D6 ultrarapid risk)",
    geriatricGuidelines: [{ type: "Beers", ruleDescription: "Constipation, falls, variable metabolism.", recommendation: "Avoid; prefer non-opioid antitussives" }] },
  { id: "bilastine", name: "Bilastine (Bilasure)", class: "2nd-generation antihistamine",
    standardDose: "20 mg OD empty stomach (non-sedating, no QT signal)" },
  { id: "rupatadine", name: "Rupatadine (Rupanex)", class: "2nd-generation antihistamine",
    standardDose: "10 mg PO OD" },

  // ============ GI ============
  { id: "misoprostol", name: "Misoprostol (Cytolog)", class: "Prostaglandin analogue",
    standardDose: "NSAID-ulcer prophylaxis 200 µg BID–QID; obstetric uses per protocol (abortifacient — never in desired pregnancy)" },
  { id: "itopride", name: "Itopride (Ganaton)", class: "Prokinetic",
    standardDose: "50 mg TID before meals" },
  { id: "levosulpiride", name: "Levosulpiride (Lesuride)", class: "Prokinetic",
    standardDose: "25 mg TID (extrapyramidal effects, prolactin rise — avoid long-term)" },
  { id: "prucalopride", name: "Prucalopride (Pruease)", class: "Prokinetic laxative",
    standardDose: "2 mg PO OD (chronic constipation)",
    renalAdjustmentLimit: 30, renalNote: "1 mg OD CrCl < 30." },
  { id: "polyethylene-glycol", name: "Polyethylene glycol (PEG / Movicol)", class: "Osmotic laxative",
    standardDose: "17 g in water OD (first-line chronic constipation, safe in elderly)" },
  { id: "bisacodyl", name: "Bisacodyl (Dulcolax)", class: "Stimulant laxative",
    standardDose: "5–10 mg PO at night or 10 mg PR" },
  { id: "ispaghula", name: "Ispaghula husk (Isabgol / Naturolax)", class: "Bulk laxative",
    standardDose: "1–2 tsp in water OD–BID with plenty of fluid" },
  { id: "mesalazine", name: "Mesalazine (Mesacol)", class: "5-ASA (IBD)",
    standardDose: "UC: 2.4–4.8 g/day divided PO ± enema (annual creatinine — interstitial nephritis)" },
  { id: "ursodeoxycholic-acid", name: "Ursodeoxycholic acid (Udiliv)", class: "Bile acid",
    standardDose: "PBC/ICP: 13–15 mg/kg/day divided" },
  { id: "pancreatin", name: "Pancreatin (Creon)", class: "Pancreatic enzymes",
    standardDose: "25,000–40,000 units lipase with each meal (chronic pancreatitis, CF)" },

  // ============ PAIN / RHEUMATOLOGY / BIOLOGICS ============
  { id: "tapentadol", name: "Tapentadol (Tydol)", class: "Opioid analgesic",
    standardDose: "50–100 mg q4–6h (max 600 mg/day); less constipation than morphine" },
  { id: "oxycodone", name: "Oxycodone", class: "Opioid analgesic",
    standardDose: "5–10 mg q4–6h PO; CR BID (cancer pain step 3)",
    renalAdjustmentLimit: 30, renalNote: "Reduce dose/extend interval in renal impairment." },
  { id: "buprenorphine", name: "Buprenorphine (Buprigesic / patch)", class: "Opioid (partial agonist)",
    standardDose: "Patch 5–20 µg/h weekly (usable in renal failure); SL for OUD per program" },
  { id: "methadone", name: "Methadone", class: "Opioid (long-acting)",
    standardDose: "Specialist only: 2.5–10 mg q8–12h analgesia (QT prolongation, long variable half-life)" },
  { id: "ketorolac", name: "Ketorolac (Ketanov)", class: "NSAID (potent, short-course)",
    standardDose: "10 mg PO q6h or 30 mg IV/IM q6h, MAXIMUM 5 days total",
    renalAdjustmentLimit: 60, renalNote: "Avoid in renal impairment — highest NSAID AKI/GI risk.",
    geriatricGuidelines: [{ type: "Beers", ruleDescription: "Highest GI bleed and AKI risk of NSAIDs.", recommendation: "Avoid in older adults" }] },
  { id: "mefenamic-acid", name: "Mefenamic acid (Meftal)", class: "NSAID",
    standardDose: "500 mg TID with food, short courses (dysmenorrhea)" },
  { id: "piroxicam", name: "Piroxicam (Dolonex)", class: "NSAID (long-acting)",
    standardDose: "20 mg OD (high GI risk — avoid in elderly)",
    geriatricGuidelines: [{ type: "Beers", ruleDescription: "Long half-life NSAID with high GI risk.", recommendation: "Avoid in older adults" }] },
  { id: "celecoxib", name: "Celecoxib (Celact)", class: "COX-2 inhibitor",
    standardDose: "100–200 mg OD–BID (lower GI risk; CV risk persists)" },
  { id: "tizanidine", name: "Tizanidine (Sirdalud)", class: "Muscle relaxant",
    standardDose: "2 mg TID → max 24 mg/day (hypotension, LFTs; CYP1A2 interaction with ciprofloxacin/fluvoxamine)" },
  { id: "chlorzoxazone", name: "Chlorzoxazone (Parafon component)", class: "Muscle relaxant",
    standardDose: "250–500 mg TID short-course" },
  { id: "tofacitinib", name: "Tofacitinib (Xeljanz / Tofajak)", class: "JAK inhibitor",
    standardDose: "5 mg PO BID (RA/UC); zoster vaccine first, lipids at 3 mo, VTE/MACE warnings",
    renalAdjustmentLimit: 40, renalNote: "5 mg OD in moderate-severe renal impairment." },
  { id: "baricitinib", name: "Baricitinib (Olumiant)", class: "JAK inhibitor",
    standardDose: "2–4 mg PO OD",
    renalAdjustmentLimit: 60, renalNote: "2 mg OD eGFR 30–60; avoid < 30." },
  { id: "adalimumab", name: "Adalimumab (Exemptia / Humira)", class: "Biologic — TNF inhibitor",
    standardDose: "40 mg SC q2wk (screen TB with CXR + IGRA and HBV before starting)" },
  { id: "etanercept", name: "Etanercept (Intacept)", class: "Biologic — TNF inhibitor",
    standardDose: "50 mg SC weekly (TB/HBV screening as for all anti-TNF)" },
  { id: "infliximab", name: "Infliximab (Remicade / Infimab)", class: "Biologic — TNF inhibitor",
    standardDose: "3–5 mg/kg IV at 0, 2, 6 wk then q8wk" },
  { id: "certolizumab", name: "Certolizumab pegol (Cimzia)", class: "Biologic — TNF inhibitor",
    standardDose: "400 mg SC at 0, 2, 4 wk then 200 mg q2wk (least placental transfer — pregnancy preferred)" },
  { id: "secukinumab", name: "Secukinumab (Scapho)", class: "Biologic — IL-17A inhibitor",
    standardDose: "300 mg SC weekly ×5 then monthly (psoriasis/PsA/axSpA); avoid in IBD" },
  { id: "ustekinumab", name: "Ustekinumab (Stelara)", class: "Biologic — IL-12/23 inhibitor",
    standardDose: "45–90 mg SC at 0, 4 wk then q12wk" },
  { id: "tocilizumab", name: "Tocilizumab (Actemra)", class: "Biologic — IL-6 inhibitor",
    standardDose: "8 mg/kg IV q4wk or 162 mg SC weekly (LFTs, lipids, neutrophils; masks fever/CRP in infection)" },
  { id: "abatacept", name: "Abatacept (Orencia)", class: "Biologic — T-cell costimulation blocker",
    standardDose: "125 mg SC weekly" },
  { id: "anakinra", name: "Anakinra (Kineret)", class: "Biologic — IL-1 antagonist",
    standardDose: "100 mg SC OD (stills/gout flares in renal-safe protocols)",
    renalAdjustmentLimit: 30, renalNote: "Alternate-day dosing CrCl < 30." },

  // ============ DERMATOLOGY / OPHTHALMOLOGY / MISC ============
  { id: "isotretinoin", name: "Isotretinoin (Sotret)", class: "Oral retinoid",
    standardDose: "0.5–1 mg/kg/day with food (severe teratogen — two contraception methods; lipids and LFTs; no vitamin A supplements)" },
  { id: "acitretin", name: "Acitretin (Aceret)", class: "Oral retinoid",
    standardDose: "25–50 mg OD with food (teratogen — 3-YEAR contraception after stopping)" },
  { id: "griseofulvin", name: "Griseofulvin (Grisovin)", class: "Antifungal (oral)",
    standardDose: "500 mg–1 g/day with fatty food ×4–8 wk (tinea capitis)" },
  { id: "permethrin", name: "Permethrin 5% (Permite)", class: "Scabicide",
    standardDose: "Apply neck-down overnight, wash after 8–12 h; repeat day 7; treat all contacts" },
  { id: "latanoprost", name: "Latanoprost eye drops (Latoprost)", class: "Prostaglandin analogue (glaucoma)",
    standardDose: "1 drop each eye at night (iris pigmentation, lash growth)" },
  { id: "timolol-eye", name: "Timolol 0.5% eye drops (Glucomol)", class: "Beta-blocker (glaucoma)",
    standardDose: "1 drop BID with punctal occlusion (systemic beta-blockade — asthma/bradycardia caution)" },
  { id: "brimonidine", name: "Brimonidine eye drops (Alphagan)", class: "Alpha-2 agonist (glaucoma)",
    standardDose: "1 drop BID–TID (never in infants — CNS depression)" },
  { id: "dorzolamide", name: "Dorzolamide eye drops (Dortas)", class: "Carbonic anhydrase inhibitor (glaucoma)",
    standardDose: "1 drop TID (sulfa allergy caution)" },
  { id: "pilocarpine", name: "Pilocarpine eye drops", class: "Miotic (glaucoma)",
    standardDose: "2% 1 drop up to QID (acute angle closure adjunct)" },
  { id: "atropine", name: "Atropine injection", class: "Anticholinergic",
    standardDose: "Bradycardia: 0.6–1 mg IV q3–5min (max 3 mg); OP poisoning: 2–5 mg IV doubling till atropinized" },
  { id: "glycopyrrolate", name: "Glycopyrrolate", class: "Anticholinergic",
    standardDose: "0.2 mg IV (secretions, with neostigmine for reversal)" },
  { id: "activated-charcoal", name: "Activated charcoal", class: "Antidote (adsorbent)",
    standardDose: "1 g/kg PO within 1 h of ingestion (protected airway only; not for corrosives/metals/alcohols)" },
  { id: "pralidoxime", name: "Pralidoxime (PAM)", class: "Antidote (OP poisoning)",
    standardDose: "30 mg/kg IV over 20 min then 8–10 mg/kg/h with atropine" },
  { id: "n-acetylcysteine-antidote", name: "N-acetylcysteine IV (paracetamol antidote)", class: "Antidote",
    standardDose: "150 mg/kg over 1 h → 50 mg/kg over 4 h → 100 mg/kg over 16 h (21-h regimen)" },

  // ============ CNS / PSYCHIATRY — remaining agents ============
  { id: "ethosuximide", name: "Ethosuximide (Zarontin)", class: "Antiepileptic (absence)",
    standardDose: "250 mg BID → 20–30 mg/kg/day (absence seizures only — gives NO generalized tonic-clonic cover)" },
  { id: "diazepam", name: "Diazepam (Valium / Calmpose)", class: "Benzodiazepine",
    standardDose: "Anxiety: 2–5 mg BID–TID; status epilepticus: 0.2 mg/kg (max 10 mg) slow IV; alcohol withdrawal per CIWA",
    geriatricGuidelines: [{ type: "Beers", ruleDescription: "Long-acting benzodiazepine — falls, delirium, dependence.", recommendation: "Avoid in older adults" }] },
  { id: "imipramine", name: "Imipramine (Depsonil)", class: "Tricyclic antidepressant",
    standardDose: "25–75 mg at night → max 200 mg; enuresis (≥ 6 y): 25–50 mg HS short courses (anticholinergic; lethal in overdose — small quantities)" },
  { id: "nortriptyline", name: "Nortriptyline (Sensival)", class: "Tricyclic antidepressant",
    standardDose: "25 mg HS → 75–150 mg (least orthostatic TCA)" },
  { id: "chlorpromazine", name: "Chlorpromazine (Largactil)", class: "Typical antipsychotic (phenothiazine)",
    standardDose: "25–100 mg TID (sedating; hypotension; intractable hiccups: 25–50 mg TID)" },
  { id: "trifluoperazine", name: "Trifluoperazine (Espazine)", class: "Typical antipsychotic",
    standardDose: "5–20 mg/day divided (more EPS, less sedation)" },
  { id: "methylphenidate", name: "Methylphenidate (Inspiral / Addwize)", class: "Stimulant (ADHD)",
    standardDose: "Children ≥ 6 y: 5 mg OD–BID → 0.3–1 mg/kg/day (max 60 mg); ER once each morning; monitor appetite, growth, BP/HR" },
  { id: "atomoxetine", name: "Atomoxetine (Attentrol / Axepta)", class: "Non-stimulant ADHD (NRI)",
    standardDose: "0.5 mg/kg/day × 1 wk → 1.2 mg/kg/day (max 100 mg); suicidal-ideation warning, LFTs if jaundice/symptoms" },
];
